/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateRewardsRequestReward.Builder.class)
public final class CreateRewardsRequestReward {
    private final Optional<Boolean> active;

    private final int cardId;

    private final Optional<String> description;

    private final String name;

    private final Optional<Integer> position;

    private final int stampsRequired;

    private final Map<String, Object> additionalProperties;

    private CreateRewardsRequestReward(
            Optional<Boolean> active,
            int cardId,
            Optional<String> description,
            String name,
            Optional<Integer> position,
            int stampsRequired,
            Map<String, Object> additionalProperties) {
        this.active = active;
        this.cardId = cardId;
        this.description = description;
        this.name = name;
        this.position = position;
        this.stampsRequired = stampsRequired;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether the reward is active and redeemable (defaults to true)
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return ID of the loyalty card this reward belongs to
     */
    @JsonProperty("card_id")
    public int getCardId() {
        return cardId;
    }

    /**
     * @return Detailed description of the reward
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Display name of the reward (e.g. 'Free Coffee')
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Display order position (lower numbers appear first)
     */
    @JsonProperty("position")
    public Optional<Integer> getPosition() {
        return position;
    }

    /**
     * @return Number of stamps needed to unlock this reward (must be &gt; 0)
     */
    @JsonProperty("stamps_required")
    public int getStampsRequired() {
        return stampsRequired;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateRewardsRequestReward && equalTo((CreateRewardsRequestReward) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateRewardsRequestReward other) {
        return active.equals(other.active)
                && cardId == other.cardId
                && description.equals(other.description)
                && name.equals(other.name)
                && position.equals(other.position)
                && stampsRequired == other.stampsRequired;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.active, this.cardId, this.description, this.name, this.position, this.stampsRequired);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CardIdStage builder() {
        return new Builder();
    }

    public interface CardIdStage {
        /**
         * <p>ID of the loyalty card this reward belongs to</p>
         */
        NameStage cardId(int cardId);

        Builder from(CreateRewardsRequestReward other);
    }

    public interface NameStage {
        /**
         * <p>Display name of the reward (e.g. 'Free Coffee')</p>
         */
        StampsRequiredStage name(@NotNull String name);
    }

    public interface StampsRequiredStage {
        /**
         * <p>Number of stamps needed to unlock this reward (must be &gt; 0)</p>
         */
        _FinalStage stampsRequired(int stampsRequired);
    }

    public interface _FinalStage {
        CreateRewardsRequestReward build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Whether the reward is active and redeemable (defaults to true)</p>
         */
        _FinalStage active(Optional<Boolean> active);

        _FinalStage active(Boolean active);

        /**
         * <p>Detailed description of the reward</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>Display order position (lower numbers appear first)</p>
         */
        _FinalStage position(Optional<Integer> position);

        _FinalStage position(Integer position);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CardIdStage, NameStage, StampsRequiredStage, _FinalStage {
        private int cardId;

        private String name;

        private int stampsRequired;

        private Optional<Integer> position = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<Boolean> active = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateRewardsRequestReward other) {
            active(other.getActive());
            cardId(other.getCardId());
            description(other.getDescription());
            name(other.getName());
            position(other.getPosition());
            stampsRequired(other.getStampsRequired());
            return this;
        }

        /**
         * <p>ID of the loyalty card this reward belongs to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("card_id")
        public NameStage cardId(int cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * <p>Display name of the reward (e.g. 'Free Coffee')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public StampsRequiredStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Number of stamps needed to unlock this reward (must be &gt; 0)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stamps_required")
        public _FinalStage stampsRequired(int stampsRequired) {
            this.stampsRequired = stampsRequired;
            return this;
        }

        /**
         * <p>Display order position (lower numbers appear first)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage position(Integer position) {
            this.position = Optional.ofNullable(position);
            return this;
        }

        /**
         * <p>Display order position (lower numbers appear first)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "position", nulls = Nulls.SKIP)
        public _FinalStage position(Optional<Integer> position) {
            this.position = position;
            return this;
        }

        /**
         * <p>Detailed description of the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Detailed description of the reward</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        /**
         * <p>Whether the reward is active and redeemable (defaults to true)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Whether the reward is active and redeemable (defaults to true)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public _FinalStage active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        @java.lang.Override
        public CreateRewardsRequestReward build() {
            return new CreateRewardsRequestReward(
                    active, cardId, description, name, position, stampsRequired, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
