/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetRewardsResponse.Builder.class)
public final class GetRewardsResponse {
    private final int accountId;

    private final boolean active;

    private final int cardId;

    private final String createdAt;

    private final String description;

    private final int id;

    private final String name;

    private final int position;

    private final int stampsRequired;

    private final String updatedAt;

    private final Map<String, Object> additionalProperties;

    private GetRewardsResponse(
            int accountId,
            boolean active,
            int cardId,
            String createdAt,
            String description,
            int id,
            String name,
            int position,
            int stampsRequired,
            String updatedAt,
            Map<String, Object> additionalProperties) {
        this.accountId = accountId;
        this.active = active;
        this.cardId = cardId;
        this.createdAt = createdAt;
        this.description = description;
        this.id = id;
        this.name = name;
        this.position = position;
        this.stampsRequired = stampsRequired;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Parent store ID
     */
    @JsonProperty("account_id")
    public int getAccountId() {
        return accountId;
    }

    /**
     * @return Whether the reward can currently be redeemed
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return ID of the loyalty card this reward belongs to
     */
    @JsonProperty("card_id")
    public int getCardId() {
        return cardId;
    }

    /**
     * @return ISO 8601 creation timestamp
     */
    @JsonProperty("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Longer description of the reward
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return Unique reward ID
     */
    @JsonProperty("id")
    public int getId() {
        return id;
    }

    /**
     * @return Display name of the reward
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Display order
     */
    @JsonProperty("position")
    public int getPosition() {
        return position;
    }

    /**
     * @return Stamps needed before the reward can be redeemed
     */
    @JsonProperty("stamps_required")
    public int getStampsRequired() {
        return stampsRequired;
    }

    /**
     * @return ISO 8601 last-update timestamp
     */
    @JsonProperty("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetRewardsResponse && equalTo((GetRewardsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetRewardsResponse other) {
        return accountId == other.accountId
                && active == other.active
                && cardId == other.cardId
                && createdAt.equals(other.createdAt)
                && description.equals(other.description)
                && id == other.id
                && name.equals(other.name)
                && position == other.position
                && stampsRequired == other.stampsRequired
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.accountId,
                this.active,
                this.cardId,
                this.createdAt,
                this.description,
                this.id,
                this.name,
                this.position,
                this.stampsRequired,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccountIdStage builder() {
        return new Builder();
    }

    public interface AccountIdStage {
        /**
         * <p>Parent store ID</p>
         */
        ActiveStage accountId(int accountId);

        Builder from(GetRewardsResponse other);
    }

    public interface ActiveStage {
        /**
         * <p>Whether the reward can currently be redeemed</p>
         */
        CardIdStage active(boolean active);
    }

    public interface CardIdStage {
        /**
         * <p>ID of the loyalty card this reward belongs to</p>
         */
        CreatedAtStage cardId(int cardId);
    }

    public interface CreatedAtStage {
        /**
         * <p>ISO 8601 creation timestamp</p>
         */
        DescriptionStage createdAt(@NotNull String createdAt);
    }

    public interface DescriptionStage {
        /**
         * <p>Longer description of the reward</p>
         */
        IdStage description(@NotNull String description);
    }

    public interface IdStage {
        /**
         * <p>Unique reward ID</p>
         */
        NameStage id(int id);
    }

    public interface NameStage {
        /**
         * <p>Display name of the reward</p>
         */
        PositionStage name(@NotNull String name);
    }

    public interface PositionStage {
        /**
         * <p>Display order</p>
         */
        StampsRequiredStage position(int position);
    }

    public interface StampsRequiredStage {
        /**
         * <p>Stamps needed before the reward can be redeemed</p>
         */
        UpdatedAtStage stampsRequired(int stampsRequired);
    }

    public interface UpdatedAtStage {
        /**
         * <p>ISO 8601 last-update timestamp</p>
         */
        _FinalStage updatedAt(@NotNull String updatedAt);
    }

    public interface _FinalStage {
        GetRewardsResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AccountIdStage,
                    ActiveStage,
                    CardIdStage,
                    CreatedAtStage,
                    DescriptionStage,
                    IdStage,
                    NameStage,
                    PositionStage,
                    StampsRequiredStage,
                    UpdatedAtStage,
                    _FinalStage {
        private int accountId;

        private boolean active;

        private int cardId;

        private String createdAt;

        private String description;

        private int id;

        private String name;

        private int position;

        private int stampsRequired;

        private String updatedAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetRewardsResponse other) {
            accountId(other.getAccountId());
            active(other.getActive());
            cardId(other.getCardId());
            createdAt(other.getCreatedAt());
            description(other.getDescription());
            id(other.getId());
            name(other.getName());
            position(other.getPosition());
            stampsRequired(other.getStampsRequired());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>Parent store ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("account_id")
        public ActiveStage accountId(int accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * <p>Whether the reward can currently be redeemed</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public CardIdStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>ID of the loyalty card this reward belongs to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("card_id")
        public CreatedAtStage cardId(int cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * <p>ISO 8601 creation timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public DescriptionStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Longer description of the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public IdStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        /**
         * <p>Unique reward ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(int id) {
            this.id = id;
            return this;
        }

        /**
         * <p>Display name of the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public PositionStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Display order</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("position")
        public StampsRequiredStage position(int position) {
            this.position = position;
            return this;
        }

        /**
         * <p>Stamps needed before the reward can be redeemed</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stamps_required")
        public UpdatedAtStage stampsRequired(int stampsRequired) {
            this.stampsRequired = stampsRequired;
            return this;
        }

        /**
         * <p>ISO 8601 last-update timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public GetRewardsResponse build() {
            return new GetRewardsResponse(
                    accountId,
                    active,
                    cardId,
                    createdAt,
                    description,
                    id,
                    name,
                    position,
                    stampsRequired,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
