/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateRewardsRequestReward.Builder.class)
public final class UpdateRewardsRequestReward {
    private final Optional<Boolean> active;

    private final Optional<String> description;

    private final Optional<String> name;

    private final Optional<Integer> position;

    private final Optional<Integer> stampsRequired;

    private final Map<String, Object> additionalProperties;

    private UpdateRewardsRequestReward(
            Optional<Boolean> active,
            Optional<String> description,
            Optional<String> name,
            Optional<Integer> position,
            Optional<Integer> stampsRequired,
            Map<String, Object> additionalProperties) {
        this.active = active;
        this.description = description;
        this.name = name;
        this.position = position;
        this.stampsRequired = stampsRequired;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether the reward is active and redeemable
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return Detailed description of the reward
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Display name of the reward
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Display order position
     */
    @JsonProperty("position")
    public Optional<Integer> getPosition() {
        return position;
    }

    /**
     * @return Number of stamps needed to unlock this reward (must be &gt; 0)
     */
    @JsonProperty("stamps_required")
    public Optional<Integer> getStampsRequired() {
        return stampsRequired;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateRewardsRequestReward && equalTo((UpdateRewardsRequestReward) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateRewardsRequestReward other) {
        return active.equals(other.active)
                && description.equals(other.description)
                && name.equals(other.name)
                && position.equals(other.position)
                && stampsRequired.equals(other.stampsRequired);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.active, this.description, this.name, this.position, this.stampsRequired);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> active = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<Integer> position = Optional.empty();

        private Optional<Integer> stampsRequired = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateRewardsRequestReward other) {
            active(other.getActive());
            description(other.getDescription());
            name(other.getName());
            position(other.getPosition());
            stampsRequired(other.getStampsRequired());
            return this;
        }

        /**
         * <p>Whether the reward is active and redeemable</p>
         */
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public Builder active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        public Builder active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Detailed description of the reward</p>
         */
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public Builder description(Optional<String> description) {
            this.description = description;
            return this;
        }

        public Builder description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Display name of the reward</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Display order position</p>
         */
        @JsonSetter(value = "position", nulls = Nulls.SKIP)
        public Builder position(Optional<Integer> position) {
            this.position = position;
            return this;
        }

        public Builder position(Integer position) {
            this.position = Optional.ofNullable(position);
            return this;
        }

        /**
         * <p>Number of stamps needed to unlock this reward (must be &gt; 0)</p>
         */
        @JsonSetter(value = "stamps_required", nulls = Nulls.SKIP)
        public Builder stampsRequired(Optional<Integer> stampsRequired) {
            this.stampsRequired = stampsRequired;
            return this;
        }

        public Builder stampsRequired(Integer stampsRequired) {
            this.stampsRequired = Optional.ofNullable(stampsRequired);
            return this;
        }

        public UpdateRewardsRequestReward build() {
            return new UpdateRewardsRequestReward(
                    active, description, name, position, stampsRequired, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
