/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.posters.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreatePostersRequestPoster.Builder.class)
public final class CreatePostersRequestPoster {
    private final Optional<Boolean> active;

    private final int cardId;

    private final Optional<String> paperSize;

    private final Optional<String> primaryColor;

    private final Optional<String> secondaryColor;

    private final Optional<String> textColor;

    private final Optional<String> title;

    private final Map<String, Object> additionalProperties;

    private CreatePostersRequestPoster(
            Optional<Boolean> active,
            int cardId,
            Optional<String> paperSize,
            Optional<String> primaryColor,
            Optional<String> secondaryColor,
            Optional<String> textColor,
            Optional<String> title,
            Map<String, Object> additionalProperties) {
        this.active = active;
        this.cardId = cardId;
        this.paperSize = paperSize;
        this.primaryColor = primaryColor;
        this.secondaryColor = secondaryColor;
        this.textColor = textColor;
        this.title = title;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether the poster is active (defaults to true)
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return ID of the loyalty card this poster links to
     */
    @JsonProperty("card_id")
    public int getCardId() {
        return cardId;
    }

    /**
     * @return Print size – one of: a4, a5, a6, letter
     */
    @JsonProperty("paper_size")
    public Optional<String> getPaperSize() {
        return paperSize;
    }

    /**
     * @return Primary brand color as a hex string (e.g. '#FF5733')
     */
    @JsonProperty("primary_color")
    public Optional<String> getPrimaryColor() {
        return primaryColor;
    }

    /**
     * @return Secondary brand color as a hex string
     */
    @JsonProperty("secondary_color")
    public Optional<String> getSecondaryColor() {
        return secondaryColor;
    }

    /**
     * @return Text color as a hex string
     */
    @JsonProperty("text_color")
    public Optional<String> getTextColor() {
        return textColor;
    }

    /**
     * @return Headline text displayed on the poster
     */
    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreatePostersRequestPoster && equalTo((CreatePostersRequestPoster) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreatePostersRequestPoster other) {
        return active.equals(other.active)
                && cardId == other.cardId
                && paperSize.equals(other.paperSize)
                && primaryColor.equals(other.primaryColor)
                && secondaryColor.equals(other.secondaryColor)
                && textColor.equals(other.textColor)
                && title.equals(other.title);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.active,
                this.cardId,
                this.paperSize,
                this.primaryColor,
                this.secondaryColor,
                this.textColor,
                this.title);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CardIdStage builder() {
        return new Builder();
    }

    public interface CardIdStage {
        /**
         * <p>ID of the loyalty card this poster links to</p>
         */
        _FinalStage cardId(int cardId);

        Builder from(CreatePostersRequestPoster other);
    }

    public interface _FinalStage {
        CreatePostersRequestPoster build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Whether the poster is active (defaults to true)</p>
         */
        _FinalStage active(Optional<Boolean> active);

        _FinalStage active(Boolean active);

        /**
         * <p>Print size – one of: a4, a5, a6, letter</p>
         */
        _FinalStage paperSize(Optional<String> paperSize);

        _FinalStage paperSize(String paperSize);

        /**
         * <p>Primary brand color as a hex string (e.g. '#FF5733')</p>
         */
        _FinalStage primaryColor(Optional<String> primaryColor);

        _FinalStage primaryColor(String primaryColor);

        /**
         * <p>Secondary brand color as a hex string</p>
         */
        _FinalStage secondaryColor(Optional<String> secondaryColor);

        _FinalStage secondaryColor(String secondaryColor);

        /**
         * <p>Text color as a hex string</p>
         */
        _FinalStage textColor(Optional<String> textColor);

        _FinalStage textColor(String textColor);

        /**
         * <p>Headline text displayed on the poster</p>
         */
        _FinalStage title(Optional<String> title);

        _FinalStage title(String title);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CardIdStage, _FinalStage {
        private int cardId;

        private Optional<String> title = Optional.empty();

        private Optional<String> textColor = Optional.empty();

        private Optional<String> secondaryColor = Optional.empty();

        private Optional<String> primaryColor = Optional.empty();

        private Optional<String> paperSize = Optional.empty();

        private Optional<Boolean> active = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreatePostersRequestPoster other) {
            active(other.getActive());
            cardId(other.getCardId());
            paperSize(other.getPaperSize());
            primaryColor(other.getPrimaryColor());
            secondaryColor(other.getSecondaryColor());
            textColor(other.getTextColor());
            title(other.getTitle());
            return this;
        }

        /**
         * <p>ID of the loyalty card this poster links to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("card_id")
        public _FinalStage cardId(int cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * <p>Headline text displayed on the poster</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>Headline text displayed on the poster</p>
         */
        @java.lang.Override
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public _FinalStage title(Optional<String> title) {
            this.title = title;
            return this;
        }

        /**
         * <p>Text color as a hex string</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage textColor(String textColor) {
            this.textColor = Optional.ofNullable(textColor);
            return this;
        }

        /**
         * <p>Text color as a hex string</p>
         */
        @java.lang.Override
        @JsonSetter(value = "text_color", nulls = Nulls.SKIP)
        public _FinalStage textColor(Optional<String> textColor) {
            this.textColor = textColor;
            return this;
        }

        /**
         * <p>Secondary brand color as a hex string</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage secondaryColor(String secondaryColor) {
            this.secondaryColor = Optional.ofNullable(secondaryColor);
            return this;
        }

        /**
         * <p>Secondary brand color as a hex string</p>
         */
        @java.lang.Override
        @JsonSetter(value = "secondary_color", nulls = Nulls.SKIP)
        public _FinalStage secondaryColor(Optional<String> secondaryColor) {
            this.secondaryColor = secondaryColor;
            return this;
        }

        /**
         * <p>Primary brand color as a hex string (e.g. '#FF5733')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage primaryColor(String primaryColor) {
            this.primaryColor = Optional.ofNullable(primaryColor);
            return this;
        }

        /**
         * <p>Primary brand color as a hex string (e.g. '#FF5733')</p>
         */
        @java.lang.Override
        @JsonSetter(value = "primary_color", nulls = Nulls.SKIP)
        public _FinalStage primaryColor(Optional<String> primaryColor) {
            this.primaryColor = primaryColor;
            return this;
        }

        /**
         * <p>Print size – one of: a4, a5, a6, letter</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage paperSize(String paperSize) {
            this.paperSize = Optional.ofNullable(paperSize);
            return this;
        }

        /**
         * <p>Print size – one of: a4, a5, a6, letter</p>
         */
        @java.lang.Override
        @JsonSetter(value = "paper_size", nulls = Nulls.SKIP)
        public _FinalStage paperSize(Optional<String> paperSize) {
            this.paperSize = paperSize;
            return this;
        }

        /**
         * <p>Whether the poster is active (defaults to true)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Whether the poster is active (defaults to true)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public _FinalStage active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        @java.lang.Override
        public CreatePostersRequestPoster build() {
            return new CreatePostersRequestPoster(
                    active, cardId, paperSize, primaryColor, secondaryColor, textColor, title, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
