/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.posters.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetPostersResponse.Builder.class)
public final class GetPostersResponse {
    private final int accountId;

    private final boolean active;

    private final int cardId;

    private final String createdAt;

    private final String displayUrl;

    private final int id;

    private final String paperSize;

    private final String primaryColor;

    private final String qrCodeUrl;

    private final String secondaryColor;

    private final String signupUrl;

    private final String textColor;

    private final String title;

    private final String updatedAt;

    private final Map<String, Object> additionalProperties;

    private GetPostersResponse(
            int accountId,
            boolean active,
            int cardId,
            String createdAt,
            String displayUrl,
            int id,
            String paperSize,
            String primaryColor,
            String qrCodeUrl,
            String secondaryColor,
            String signupUrl,
            String textColor,
            String title,
            String updatedAt,
            Map<String, Object> additionalProperties) {
        this.accountId = accountId;
        this.active = active;
        this.cardId = cardId;
        this.createdAt = createdAt;
        this.displayUrl = displayUrl;
        this.id = id;
        this.paperSize = paperSize;
        this.primaryColor = primaryColor;
        this.qrCodeUrl = qrCodeUrl;
        this.secondaryColor = secondaryColor;
        this.signupUrl = signupUrl;
        this.textColor = textColor;
        this.title = title;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Parent store ID
     */
    @JsonProperty("account_id")
    public int getAccountId() {
        return accountId;
    }

    /**
     * @return Whether the public signup URL is live
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return Loyalty card customers are signed up to
     */
    @JsonProperty("card_id")
    public int getCardId() {
        return cardId;
    }

    /**
     * @return ISO 8601 creation timestamp
     */
    @JsonProperty("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * @return URL of the on screen version of the poster
     */
    @JsonProperty("display_url")
    public String getDisplayUrl() {
        return displayUrl;
    }

    /**
     * @return Unique poster ID
     */
    @JsonProperty("id")
    public int getId() {
        return id;
    }

    /**
     * @return Paper size the poster is laid out for
     */
    @JsonProperty("paper_size")
    public String getPaperSize() {
        return paperSize;
    }

    /**
     * @return Hex colour for the poster background
     */
    @JsonProperty("primary_color")
    public String getPrimaryColor() {
        return primaryColor;
    }

    /**
     * @return URL encoded in the QR code
     */
    @JsonProperty("qr_code_url")
    public String getQrCodeUrl() {
        return qrCodeUrl;
    }

    /**
     * @return Hex accent colour
     */
    @JsonProperty("secondary_color")
    public String getSecondaryColor() {
        return secondaryColor;
    }

    /**
     * @return Public URL the QR code points at
     */
    @JsonProperty("signup_url")
    public String getSignupUrl() {
        return signupUrl;
    }

    /**
     * @return Hex colour for poster text
     */
    @JsonProperty("text_color")
    public String getTextColor() {
        return textColor;
    }

    /**
     * @return Heading printed on the poster
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    /**
     * @return ISO 8601 last-update timestamp
     */
    @JsonProperty("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetPostersResponse && equalTo((GetPostersResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetPostersResponse other) {
        return accountId == other.accountId
                && active == other.active
                && cardId == other.cardId
                && createdAt.equals(other.createdAt)
                && displayUrl.equals(other.displayUrl)
                && id == other.id
                && paperSize.equals(other.paperSize)
                && primaryColor.equals(other.primaryColor)
                && qrCodeUrl.equals(other.qrCodeUrl)
                && secondaryColor.equals(other.secondaryColor)
                && signupUrl.equals(other.signupUrl)
                && textColor.equals(other.textColor)
                && title.equals(other.title)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.accountId,
                this.active,
                this.cardId,
                this.createdAt,
                this.displayUrl,
                this.id,
                this.paperSize,
                this.primaryColor,
                this.qrCodeUrl,
                this.secondaryColor,
                this.signupUrl,
                this.textColor,
                this.title,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccountIdStage builder() {
        return new Builder();
    }

    public interface AccountIdStage {
        /**
         * <p>Parent store ID</p>
         */
        ActiveStage accountId(int accountId);

        Builder from(GetPostersResponse other);
    }

    public interface ActiveStage {
        /**
         * <p>Whether the public signup URL is live</p>
         */
        CardIdStage active(boolean active);
    }

    public interface CardIdStage {
        /**
         * <p>Loyalty card customers are signed up to</p>
         */
        CreatedAtStage cardId(int cardId);
    }

    public interface CreatedAtStage {
        /**
         * <p>ISO 8601 creation timestamp</p>
         */
        DisplayUrlStage createdAt(@NotNull String createdAt);
    }

    public interface DisplayUrlStage {
        /**
         * <p>URL of the on screen version of the poster</p>
         */
        IdStage displayUrl(@NotNull String displayUrl);
    }

    public interface IdStage {
        /**
         * <p>Unique poster ID</p>
         */
        PaperSizeStage id(int id);
    }

    public interface PaperSizeStage {
        /**
         * <p>Paper size the poster is laid out for</p>
         */
        PrimaryColorStage paperSize(@NotNull String paperSize);
    }

    public interface PrimaryColorStage {
        /**
         * <p>Hex colour for the poster background</p>
         */
        QrCodeUrlStage primaryColor(@NotNull String primaryColor);
    }

    public interface QrCodeUrlStage {
        /**
         * <p>URL encoded in the QR code</p>
         */
        SecondaryColorStage qrCodeUrl(@NotNull String qrCodeUrl);
    }

    public interface SecondaryColorStage {
        /**
         * <p>Hex accent colour</p>
         */
        SignupUrlStage secondaryColor(@NotNull String secondaryColor);
    }

    public interface SignupUrlStage {
        /**
         * <p>Public URL the QR code points at</p>
         */
        TextColorStage signupUrl(@NotNull String signupUrl);
    }

    public interface TextColorStage {
        /**
         * <p>Hex colour for poster text</p>
         */
        TitleStage textColor(@NotNull String textColor);
    }

    public interface TitleStage {
        /**
         * <p>Heading printed on the poster</p>
         */
        UpdatedAtStage title(@NotNull String title);
    }

    public interface UpdatedAtStage {
        /**
         * <p>ISO 8601 last-update timestamp</p>
         */
        _FinalStage updatedAt(@NotNull String updatedAt);
    }

    public interface _FinalStage {
        GetPostersResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AccountIdStage,
                    ActiveStage,
                    CardIdStage,
                    CreatedAtStage,
                    DisplayUrlStage,
                    IdStage,
                    PaperSizeStage,
                    PrimaryColorStage,
                    QrCodeUrlStage,
                    SecondaryColorStage,
                    SignupUrlStage,
                    TextColorStage,
                    TitleStage,
                    UpdatedAtStage,
                    _FinalStage {
        private int accountId;

        private boolean active;

        private int cardId;

        private String createdAt;

        private String displayUrl;

        private int id;

        private String paperSize;

        private String primaryColor;

        private String qrCodeUrl;

        private String secondaryColor;

        private String signupUrl;

        private String textColor;

        private String title;

        private String updatedAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetPostersResponse other) {
            accountId(other.getAccountId());
            active(other.getActive());
            cardId(other.getCardId());
            createdAt(other.getCreatedAt());
            displayUrl(other.getDisplayUrl());
            id(other.getId());
            paperSize(other.getPaperSize());
            primaryColor(other.getPrimaryColor());
            qrCodeUrl(other.getQrCodeUrl());
            secondaryColor(other.getSecondaryColor());
            signupUrl(other.getSignupUrl());
            textColor(other.getTextColor());
            title(other.getTitle());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>Parent store ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("account_id")
        public ActiveStage accountId(int accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * <p>Whether the public signup URL is live</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public CardIdStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>Loyalty card customers are signed up to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("card_id")
        public CreatedAtStage cardId(int cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * <p>ISO 8601 creation timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public DisplayUrlStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>URL of the on screen version of the poster</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("display_url")
        public IdStage displayUrl(@NotNull String displayUrl) {
            this.displayUrl = Objects.requireNonNull(displayUrl, "displayUrl must not be null");
            return this;
        }

        /**
         * <p>Unique poster ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public PaperSizeStage id(int id) {
            this.id = id;
            return this;
        }

        /**
         * <p>Paper size the poster is laid out for</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("paper_size")
        public PrimaryColorStage paperSize(@NotNull String paperSize) {
            this.paperSize = Objects.requireNonNull(paperSize, "paperSize must not be null");
            return this;
        }

        /**
         * <p>Hex colour for the poster background</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("primary_color")
        public QrCodeUrlStage primaryColor(@NotNull String primaryColor) {
            this.primaryColor = Objects.requireNonNull(primaryColor, "primaryColor must not be null");
            return this;
        }

        /**
         * <p>URL encoded in the QR code</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("qr_code_url")
        public SecondaryColorStage qrCodeUrl(@NotNull String qrCodeUrl) {
            this.qrCodeUrl = Objects.requireNonNull(qrCodeUrl, "qrCodeUrl must not be null");
            return this;
        }

        /**
         * <p>Hex accent colour</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("secondary_color")
        public SignupUrlStage secondaryColor(@NotNull String secondaryColor) {
            this.secondaryColor = Objects.requireNonNull(secondaryColor, "secondaryColor must not be null");
            return this;
        }

        /**
         * <p>Public URL the QR code points at</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signup_url")
        public TextColorStage signupUrl(@NotNull String signupUrl) {
            this.signupUrl = Objects.requireNonNull(signupUrl, "signupUrl must not be null");
            return this;
        }

        /**
         * <p>Hex colour for poster text</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("text_color")
        public TitleStage textColor(@NotNull String textColor) {
            this.textColor = Objects.requireNonNull(textColor, "textColor must not be null");
            return this;
        }

        /**
         * <p>Heading printed on the poster</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public UpdatedAtStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>ISO 8601 last-update timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public GetPostersResponse build() {
            return new GetPostersResponse(
                    accountId,
                    active,
                    cardId,
                    createdAt,
                    displayUrl,
                    id,
                    paperSize,
                    primaryColor,
                    qrCodeUrl,
                    secondaryColor,
                    signupUrl,
                    textColor,
                    title,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
