/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.posters.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdatePostersRequestPoster.Builder.class)
public final class UpdatePostersRequestPoster {
    private final Optional<Boolean> active;

    private final Optional<String> contactCollectionMode;

    private final Optional<Double> minimumAge;

    private final Optional<String> paperSize;

    private final Optional<String> primaryColor;

    private final Optional<Boolean> requireBirthday;

    private final Optional<Boolean> requireEmail;

    private final Optional<Boolean> requirePhone;

    private final Optional<String> secondaryColor;

    private final Optional<String> textColor;

    private final Optional<String> title;

    private final Map<String, Object> additionalProperties;

    private UpdatePostersRequestPoster(
            Optional<Boolean> active,
            Optional<String> contactCollectionMode,
            Optional<Double> minimumAge,
            Optional<String> paperSize,
            Optional<String> primaryColor,
            Optional<Boolean> requireBirthday,
            Optional<Boolean> requireEmail,
            Optional<Boolean> requirePhone,
            Optional<String> secondaryColor,
            Optional<String> textColor,
            Optional<String> title,
            Map<String, Object> additionalProperties) {
        this.active = active;
        this.contactCollectionMode = contactCollectionMode;
        this.minimumAge = minimumAge;
        this.paperSize = paperSize;
        this.primaryColor = primaryColor;
        this.requireBirthday = requireBirthday;
        this.requireEmail = requireEmail;
        this.requirePhone = requirePhone;
        this.secondaryColor = secondaryColor;
        this.textColor = textColor;
        this.title = title;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether the poster is active
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return Which contact fields appear on the public signup form
     */
    @JsonProperty("contact_collection_mode")
    public Optional<String> getContactCollectionMode() {
        return contactCollectionMode;
    }

    /**
     * @return Minimum customer age required for signup. Requires require_birthday to be true.
     */
    @JsonProperty("minimum_age")
    public Optional<Double> getMinimumAge() {
        return minimumAge;
    }

    /**
     * @return Print size – one of: a4, a5, a6, letter
     */
    @JsonProperty("paper_size")
    public Optional<String> getPaperSize() {
        return paperSize;
    }

    /**
     * @return Primary brand color as a hex string
     */
    @JsonProperty("primary_color")
    public Optional<String> getPrimaryColor() {
        return primaryColor;
    }

    /**
     * @return Whether date of birth is required on the public signup form
     */
    @JsonProperty("require_birthday")
    public Optional<Boolean> getRequireBirthday() {
        return requireBirthday;
    }

    /**
     * @return Whether email is required when it is collected
     */
    @JsonProperty("require_email")
    public Optional<Boolean> getRequireEmail() {
        return requireEmail;
    }

    /**
     * @return Whether phone number is required when it is collected
     */
    @JsonProperty("require_phone")
    public Optional<Boolean> getRequirePhone() {
        return requirePhone;
    }

    /**
     * @return Secondary brand color as a hex string
     */
    @JsonProperty("secondary_color")
    public Optional<String> getSecondaryColor() {
        return secondaryColor;
    }

    /**
     * @return Text color as a hex string
     */
    @JsonProperty("text_color")
    public Optional<String> getTextColor() {
        return textColor;
    }

    /**
     * @return Headline text displayed on the poster
     */
    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdatePostersRequestPoster && equalTo((UpdatePostersRequestPoster) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdatePostersRequestPoster other) {
        return active.equals(other.active)
                && contactCollectionMode.equals(other.contactCollectionMode)
                && minimumAge.equals(other.minimumAge)
                && paperSize.equals(other.paperSize)
                && primaryColor.equals(other.primaryColor)
                && requireBirthday.equals(other.requireBirthday)
                && requireEmail.equals(other.requireEmail)
                && requirePhone.equals(other.requirePhone)
                && secondaryColor.equals(other.secondaryColor)
                && textColor.equals(other.textColor)
                && title.equals(other.title);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.active,
                this.contactCollectionMode,
                this.minimumAge,
                this.paperSize,
                this.primaryColor,
                this.requireBirthday,
                this.requireEmail,
                this.requirePhone,
                this.secondaryColor,
                this.textColor,
                this.title);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> active = Optional.empty();

        private Optional<String> contactCollectionMode = Optional.empty();

        private Optional<Double> minimumAge = Optional.empty();

        private Optional<String> paperSize = Optional.empty();

        private Optional<String> primaryColor = Optional.empty();

        private Optional<Boolean> requireBirthday = Optional.empty();

        private Optional<Boolean> requireEmail = Optional.empty();

        private Optional<Boolean> requirePhone = Optional.empty();

        private Optional<String> secondaryColor = Optional.empty();

        private Optional<String> textColor = Optional.empty();

        private Optional<String> title = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdatePostersRequestPoster other) {
            active(other.getActive());
            contactCollectionMode(other.getContactCollectionMode());
            minimumAge(other.getMinimumAge());
            paperSize(other.getPaperSize());
            primaryColor(other.getPrimaryColor());
            requireBirthday(other.getRequireBirthday());
            requireEmail(other.getRequireEmail());
            requirePhone(other.getRequirePhone());
            secondaryColor(other.getSecondaryColor());
            textColor(other.getTextColor());
            title(other.getTitle());
            return this;
        }

        /**
         * <p>Whether the poster is active</p>
         */
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public Builder active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        public Builder active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Which contact fields appear on the public signup form</p>
         */
        @JsonSetter(value = "contact_collection_mode", nulls = Nulls.SKIP)
        public Builder contactCollectionMode(Optional<String> contactCollectionMode) {
            this.contactCollectionMode = contactCollectionMode;
            return this;
        }

        public Builder contactCollectionMode(String contactCollectionMode) {
            this.contactCollectionMode = Optional.ofNullable(contactCollectionMode);
            return this;
        }

        /**
         * <p>Minimum customer age required for signup. Requires require_birthday to be true.</p>
         */
        @JsonSetter(value = "minimum_age", nulls = Nulls.SKIP)
        public Builder minimumAge(Optional<Double> minimumAge) {
            this.minimumAge = minimumAge;
            return this;
        }

        public Builder minimumAge(Double minimumAge) {
            this.minimumAge = Optional.ofNullable(minimumAge);
            return this;
        }

        /**
         * <p>Print size – one of: a4, a5, a6, letter</p>
         */
        @JsonSetter(value = "paper_size", nulls = Nulls.SKIP)
        public Builder paperSize(Optional<String> paperSize) {
            this.paperSize = paperSize;
            return this;
        }

        public Builder paperSize(String paperSize) {
            this.paperSize = Optional.ofNullable(paperSize);
            return this;
        }

        /**
         * <p>Primary brand color as a hex string</p>
         */
        @JsonSetter(value = "primary_color", nulls = Nulls.SKIP)
        public Builder primaryColor(Optional<String> primaryColor) {
            this.primaryColor = primaryColor;
            return this;
        }

        public Builder primaryColor(String primaryColor) {
            this.primaryColor = Optional.ofNullable(primaryColor);
            return this;
        }

        /**
         * <p>Whether date of birth is required on the public signup form</p>
         */
        @JsonSetter(value = "require_birthday", nulls = Nulls.SKIP)
        public Builder requireBirthday(Optional<Boolean> requireBirthday) {
            this.requireBirthday = requireBirthday;
            return this;
        }

        public Builder requireBirthday(Boolean requireBirthday) {
            this.requireBirthday = Optional.ofNullable(requireBirthday);
            return this;
        }

        /**
         * <p>Whether email is required when it is collected</p>
         */
        @JsonSetter(value = "require_email", nulls = Nulls.SKIP)
        public Builder requireEmail(Optional<Boolean> requireEmail) {
            this.requireEmail = requireEmail;
            return this;
        }

        public Builder requireEmail(Boolean requireEmail) {
            this.requireEmail = Optional.ofNullable(requireEmail);
            return this;
        }

        /**
         * <p>Whether phone number is required when it is collected</p>
         */
        @JsonSetter(value = "require_phone", nulls = Nulls.SKIP)
        public Builder requirePhone(Optional<Boolean> requirePhone) {
            this.requirePhone = requirePhone;
            return this;
        }

        public Builder requirePhone(Boolean requirePhone) {
            this.requirePhone = Optional.ofNullable(requirePhone);
            return this;
        }

        /**
         * <p>Secondary brand color as a hex string</p>
         */
        @JsonSetter(value = "secondary_color", nulls = Nulls.SKIP)
        public Builder secondaryColor(Optional<String> secondaryColor) {
            this.secondaryColor = secondaryColor;
            return this;
        }

        public Builder secondaryColor(String secondaryColor) {
            this.secondaryColor = Optional.ofNullable(secondaryColor);
            return this;
        }

        /**
         * <p>Text color as a hex string</p>
         */
        @JsonSetter(value = "text_color", nulls = Nulls.SKIP)
        public Builder textColor(Optional<String> textColor) {
            this.textColor = textColor;
            return this;
        }

        public Builder textColor(String textColor) {
            this.textColor = Optional.ofNullable(textColor);
            return this;
        }

        /**
         * <p>Headline text displayed on the poster</p>
         */
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public Builder title(Optional<String> title) {
            this.title = title;
            return this;
        }

        public Builder title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        public UpdatePostersRequestPoster build() {
            return new UpdatePostersRequestPoster(
                    active,
                    contactCollectionMode,
                    minimumAge,
                    paperSize,
                    primaryColor,
                    requireBirthday,
                    requireEmail,
                    requirePhone,
                    secondaryColor,
                    textColor,
                    title,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
