/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.stores;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.LealApiException;
import com.getleal.api.core.LealException;
import com.getleal.api.core.LealHttpResponse;
import com.getleal.api.core.MediaTypes;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.core.RetryInterceptor;
import com.getleal.api.errors.GoneError;
import com.getleal.api.errors.NotFoundError;
import com.getleal.api.errors.TooManyRequestsError;
import com.getleal.api.errors.UnauthorizedError;
import com.getleal.api.errors.UnprocessableEntityError;
import com.getleal.api.resources.stores.requests.GetStoresRequest;
import com.getleal.api.resources.stores.requests.UpdateStoresRequest;
import com.getleal.api.resources.stores.types.GetStoresResponse;
import com.getleal.api.resources.stores.types.ListStoresResponseItem;
import com.getleal.api.resources.stores.types.UpdateStoresResponse;
import com.getleal.api.types.Error;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawStoresClient {
    protected final ClientOptions clientOptions;

    public RawStoresClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.
     */
    public LealHttpResponse<List<ListStoresResponseItem>> list() {
        return list(null);
    }

    /**
     * Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.
     */
    public LealHttpResponse<List<ListStoresResponseItem>> list(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, new TypeReference<List<ListStoresResponseItem>>() {}),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 410:
                        throw new GoneError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public LealHttpResponse<GetStoresResponse> get(int id) {
        return get(id, GetStoresRequest.builder().build());
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public LealHttpResponse<GetStoresResponse> get(int id, RequestOptions requestOptions) {
        return get(id, GetStoresRequest.builder().build(), requestOptions);
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public LealHttpResponse<GetStoresResponse> get(int id, GetStoresRequest request) {
        return get(id, request, null);
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public LealHttpResponse<GetStoresResponse> get(int id, GetStoresRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetStoresResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 410:
                        throw new GoneError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates the store's name or store_name. Use <code>store_name</code> for the public-facing name displayed to customers.
     */
    public LealHttpResponse<UpdateStoresResponse> update(int id, UpdateStoresRequest request) {
        return update(id, request, null);
    }

    /**
     * Updates the store's name or store_name. Use <code>store_name</code> for the public-facing name displayed to customers.
     */
    public LealHttpResponse<UpdateStoresResponse> update(
            int id, UpdateStoresRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateStoresResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 410:
                        throw new GoneError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }
}
