/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.stores;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.stores.requests.GetStoresRequest;
import com.getleal.api.resources.stores.requests.UpdateStoresRequest;
import com.getleal.api.resources.stores.types.GetStoresResponse;
import com.getleal.api.resources.stores.types.ListStoresResponseItem;
import com.getleal.api.resources.stores.types.UpdateStoresResponse;
import java.util.List;

public class StoresClient {
    protected final ClientOptions clientOptions;

    private final RawStoresClient rawClient;

    public StoresClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawStoresClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawStoresClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.
     */
    public List<ListStoresResponseItem> list() {
        return this.rawClient.list().body();
    }

    /**
     * Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.
     */
    public List<ListStoresResponseItem> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public GetStoresResponse get(int id) {
        return this.rawClient.get(id).body();
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public GetStoresResponse get(int id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public GetStoresResponse get(int id, GetStoresRequest request) {
        return this.rawClient.get(id, request).body();
    }

    /**
     * Returns detailed information for a single store, including summary counts for its associated resources.
     */
    public GetStoresResponse get(int id, GetStoresRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(id, request, requestOptions).body();
    }

    /**
     * Updates the store's name or store_name. Use <code>store_name</code> for the public-facing name displayed to customers.
     */
    public UpdateStoresResponse update(int id, UpdateStoresRequest request) {
        return this.rawClient.update(id, request).body();
    }

    /**
     * Updates the store's name or store_name. Use <code>store_name</code> for the public-facing name displayed to customers.
     */
    public UpdateStoresResponse update(int id, UpdateStoresRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).body();
    }
}
