/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.Suppliers;
import com.getleal.api.resources.cards.AsyncCardsClient;
import com.getleal.api.resources.customercards.AsyncCustomerCardsClient;
import com.getleal.api.resources.customers.AsyncCustomersClient;
import com.getleal.api.resources.locations.AsyncLocationsClient;
import com.getleal.api.resources.posters.AsyncPostersClient;
import com.getleal.api.resources.rewards.AsyncRewardsClient;
import com.getleal.api.resources.status.AsyncStatusClient;
import com.getleal.api.resources.stores.AsyncStoresClient;
import java.util.function.Supplier;

public class AsyncLeal {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncStoresClient> storesClient;

    protected final Supplier<AsyncCardsClient> cardsClient;

    protected final Supplier<AsyncCustomersClient> customersClient;

    protected final Supplier<AsyncCustomerCardsClient> customerCardsClient;

    protected final Supplier<AsyncLocationsClient> locationsClient;

    protected final Supplier<AsyncPostersClient> postersClient;

    protected final Supplier<AsyncRewardsClient> rewardsClient;

    protected final Supplier<AsyncStatusClient> statusClient;

    public AsyncLeal(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.storesClient = Suppliers.memoize(() -> new AsyncStoresClient(clientOptions));
        this.cardsClient = Suppliers.memoize(() -> new AsyncCardsClient(clientOptions));
        this.customersClient = Suppliers.memoize(() -> new AsyncCustomersClient(clientOptions));
        this.customerCardsClient = Suppliers.memoize(() -> new AsyncCustomerCardsClient(clientOptions));
        this.locationsClient = Suppliers.memoize(() -> new AsyncLocationsClient(clientOptions));
        this.postersClient = Suppliers.memoize(() -> new AsyncPostersClient(clientOptions));
        this.rewardsClient = Suppliers.memoize(() -> new AsyncRewardsClient(clientOptions));
        this.statusClient = Suppliers.memoize(() -> new AsyncStatusClient(clientOptions));
    }

    public AsyncStoresClient stores() {
        return this.storesClient.get();
    }

    public AsyncCardsClient cards() {
        return this.cardsClient.get();
    }

    public AsyncCustomersClient customers() {
        return this.customersClient.get();
    }

    public AsyncCustomerCardsClient customerCards() {
        return this.customerCardsClient.get();
    }

    public AsyncLocationsClient locations() {
        return this.locationsClient.get();
    }

    public AsyncPostersClient posters() {
        return this.postersClient.get();
    }

    public AsyncRewardsClient rewards() {
        return this.rewardsClient.get();
    }

    public AsyncStatusClient status() {
        return this.statusClient.get();
    }

    public static AsyncLealBuilder builder() {
        return new AsyncLealBuilder();
    }
}
