/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.Suppliers;
import com.getleal.api.resources.cards.CardsClient;
import com.getleal.api.resources.customercards.CustomerCardsClient;
import com.getleal.api.resources.customers.CustomersClient;
import com.getleal.api.resources.locations.LocationsClient;
import com.getleal.api.resources.posters.PostersClient;
import com.getleal.api.resources.rewards.RewardsClient;
import com.getleal.api.resources.status.StatusClient;
import com.getleal.api.resources.stores.StoresClient;
import java.util.function.Supplier;

public class Leal {
    protected final ClientOptions clientOptions;

    protected final Supplier<StoresClient> storesClient;

    protected final Supplier<CardsClient> cardsClient;

    protected final Supplier<CustomersClient> customersClient;

    protected final Supplier<CustomerCardsClient> customerCardsClient;

    protected final Supplier<LocationsClient> locationsClient;

    protected final Supplier<PostersClient> postersClient;

    protected final Supplier<RewardsClient> rewardsClient;

    protected final Supplier<StatusClient> statusClient;

    public Leal(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.storesClient = Suppliers.memoize(() -> new StoresClient(clientOptions));
        this.cardsClient = Suppliers.memoize(() -> new CardsClient(clientOptions));
        this.customersClient = Suppliers.memoize(() -> new CustomersClient(clientOptions));
        this.customerCardsClient = Suppliers.memoize(() -> new CustomerCardsClient(clientOptions));
        this.locationsClient = Suppliers.memoize(() -> new LocationsClient(clientOptions));
        this.postersClient = Suppliers.memoize(() -> new PostersClient(clientOptions));
        this.rewardsClient = Suppliers.memoize(() -> new RewardsClient(clientOptions));
        this.statusClient = Suppliers.memoize(() -> new StatusClient(clientOptions));
    }

    public StoresClient stores() {
        return this.storesClient.get();
    }

    public CardsClient cards() {
        return this.cardsClient.get();
    }

    public CustomersClient customers() {
        return this.customersClient.get();
    }

    public CustomerCardsClient customerCards() {
        return this.customerCardsClient.get();
    }

    public LocationsClient locations() {
        return this.locationsClient.get();
    }

    public PostersClient posters() {
        return this.postersClient.get();
    }

    public RewardsClient rewards() {
        return this.rewardsClient.get();
    }

    public StatusClient status() {
        return this.statusClient.get();
    }

    public static LealBuilder builder() {
        return new LealBuilder();
    }
}
