/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.stores.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.resources.stores.types.UpdateStoresRequestAccount;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateStoresRequest.Builder.class)
public final class UpdateStoresRequest {
    private final UpdateStoresRequestAccount account;

    private final Map<String, Object> additionalProperties;

    private UpdateStoresRequest(UpdateStoresRequestAccount account, Map<String, Object> additionalProperties) {
        this.account = account;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("account")
    public UpdateStoresRequestAccount getAccount() {
        return account;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateStoresRequest && equalTo((UpdateStoresRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateStoresRequest other) {
        return account.equals(other.account);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.account);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccountStage builder() {
        return new Builder();
    }

    public interface AccountStage {
        _FinalStage account(@NotNull UpdateStoresRequestAccount account);

        Builder from(UpdateStoresRequest other);
    }

    public interface _FinalStage {
        UpdateStoresRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AccountStage, _FinalStage {
        private UpdateStoresRequestAccount account;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateStoresRequest other) {
            account(other.getAccount());
            return this;
        }

        @java.lang.Override
        @JsonSetter("account")
        public _FinalStage account(@NotNull UpdateStoresRequestAccount account) {
            this.account = Objects.requireNonNull(account, "account must not be null");
            return this;
        }

        @java.lang.Override
        public UpdateStoresRequest build() {
            return new UpdateStoresRequest(account, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
