/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customers.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateCustomersRequestCustomer.Builder.class)
public final class CreateCustomersRequestCustomer {
    private final Optional<String> birthday;

    private final Optional<String> email;

    private final Optional<List<String>> externalReferences;

    private final String firstName;

    private final Optional<String> lastName;

    private final Optional<Map<String, Object>> metadata;

    private final Optional<String> phone;

    private final Map<String, Object> additionalProperties;

    private CreateCustomersRequestCustomer(
            Optional<String> birthday,
            Optional<String> email,
            Optional<List<String>> externalReferences,
            String firstName,
            Optional<String> lastName,
            Optional<Map<String, Object>> metadata,
            Optional<String> phone,
            Map<String, Object> additionalProperties) {
        this.birthday = birthday;
        this.email = email;
        this.externalReferences = externalReferences;
        this.firstName = firstName;
        this.lastName = lastName;
        this.metadata = metadata;
        this.phone = phone;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Customer's birthday (YYYY-MM-DD)
     */
    @JsonProperty("birthday")
    public Optional<String> getBirthday() {
        return birthday;
    }

    /**
     * @return Customer's email address (unique per store; required if phone is blank)
     */
    @JsonProperty("email")
    public Optional<String> getEmail() {
        return email;
    }

    /**
     * @return Array of <code>{source, external_id, metadata}</code> objects linking this customer to records in external systems
     */
    @JsonProperty("external_references")
    public Optional<List<String>> getExternalReferences() {
        return externalReferences;
    }

    /**
     * @return Customer's first name
     */
    @JsonProperty("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * @return Customer's last name
     */
    @JsonProperty("last_name")
    public Optional<String> getLastName() {
        return lastName;
    }

    /**
     * @return Free-form JSON object of additional per-customer attributes
     */
    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    /**
     * @return Customer's phone number (unique per store; required if email is blank)
     */
    @JsonProperty("phone")
    public Optional<String> getPhone() {
        return phone;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateCustomersRequestCustomer && equalTo((CreateCustomersRequestCustomer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateCustomersRequestCustomer other) {
        return birthday.equals(other.birthday)
                && email.equals(other.email)
                && externalReferences.equals(other.externalReferences)
                && firstName.equals(other.firstName)
                && lastName.equals(other.lastName)
                && metadata.equals(other.metadata)
                && phone.equals(other.phone);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.birthday,
                this.email,
                this.externalReferences,
                this.firstName,
                this.lastName,
                this.metadata,
                this.phone);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FirstNameStage builder() {
        return new Builder();
    }

    public interface FirstNameStage {
        /**
         * <p>Customer's first name</p>
         */
        _FinalStage firstName(@NotNull String firstName);

        Builder from(CreateCustomersRequestCustomer other);
    }

    public interface _FinalStage {
        CreateCustomersRequestCustomer build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Customer's birthday (YYYY-MM-DD)</p>
         */
        _FinalStage birthday(Optional<String> birthday);

        _FinalStage birthday(String birthday);

        /**
         * <p>Customer's email address (unique per store; required if phone is blank)</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        /**
         * <p>Array of <code>{source, external_id, metadata}</code> objects linking this customer to records in external systems</p>
         */
        _FinalStage externalReferences(Optional<List<String>> externalReferences);

        _FinalStage externalReferences(List<String> externalReferences);

        /**
         * <p>Customer's last name</p>
         */
        _FinalStage lastName(Optional<String> lastName);

        _FinalStage lastName(String lastName);

        /**
         * <p>Free-form JSON object of additional per-customer attributes</p>
         */
        _FinalStage metadata(Optional<Map<String, Object>> metadata);

        _FinalStage metadata(Map<String, Object> metadata);

        /**
         * <p>Customer's phone number (unique per store; required if email is blank)</p>
         */
        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FirstNameStage, _FinalStage {
        private String firstName;

        private Optional<String> phone = Optional.empty();

        private Optional<Map<String, Object>> metadata = Optional.empty();

        private Optional<String> lastName = Optional.empty();

        private Optional<List<String>> externalReferences = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<String> birthday = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateCustomersRequestCustomer other) {
            birthday(other.getBirthday());
            email(other.getEmail());
            externalReferences(other.getExternalReferences());
            firstName(other.getFirstName());
            lastName(other.getLastName());
            metadata(other.getMetadata());
            phone(other.getPhone());
            return this;
        }

        /**
         * <p>Customer's first name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("first_name")
        public _FinalStage firstName(@NotNull String firstName) {
            this.firstName = Objects.requireNonNull(firstName, "firstName must not be null");
            return this;
        }

        /**
         * <p>Customer's phone number (unique per store; required if email is blank)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>Customer's phone number (unique per store; required if email is blank)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        /**
         * <p>Free-form JSON object of additional per-customer attributes</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(Map<String, Object> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * <p>Free-form JSON object of additional per-customer attributes</p>
         */
        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * <p>Customer's last name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastName(String lastName) {
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        /**
         * <p>Customer's last name</p>
         */
        @java.lang.Override
        @JsonSetter(value = "last_name", nulls = Nulls.SKIP)
        public _FinalStage lastName(Optional<String> lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * <p>Array of <code>{source, external_id, metadata}</code> objects linking this customer to records in external systems</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalReferences(List<String> externalReferences) {
            this.externalReferences = Optional.ofNullable(externalReferences);
            return this;
        }

        /**
         * <p>Array of <code>{source, external_id, metadata}</code> objects linking this customer to records in external systems</p>
         */
        @java.lang.Override
        @JsonSetter(value = "external_references", nulls = Nulls.SKIP)
        public _FinalStage externalReferences(Optional<List<String>> externalReferences) {
            this.externalReferences = externalReferences;
            return this;
        }

        /**
         * <p>Customer's email address (unique per store; required if phone is blank)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Customer's email address (unique per store; required if phone is blank)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        /**
         * <p>Customer's birthday (YYYY-MM-DD)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage birthday(String birthday) {
            this.birthday = Optional.ofNullable(birthday);
            return this;
        }

        /**
         * <p>Customer's birthday (YYYY-MM-DD)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "birthday", nulls = Nulls.SKIP)
        public _FinalStage birthday(Optional<String> birthday) {
            this.birthday = birthday;
            return this;
        }

        @java.lang.Override
        public CreateCustomersRequestCustomer build() {
            return new CreateCustomersRequestCustomer(
                    birthday, email, externalReferences, firstName, lastName, metadata, phone, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
