/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customers.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetCustomersResponse.Builder.class)
public final class GetCustomersResponse {
    private final int accountId;

    private final String birthday;

    private final String createdAt;

    private final List<String> customerCards;

    private final String email;

    private final List<String> externalReferences;

    private final String firstName;

    private final int id;

    private final String lastName;

    private final Map<String, Object> metadata;

    private final String phone;

    private final int stampCount;

    private final String updatedAt;

    private final Map<String, Object> additionalProperties;

    private GetCustomersResponse(
            int accountId,
            String birthday,
            String createdAt,
            List<String> customerCards,
            String email,
            List<String> externalReferences,
            String firstName,
            int id,
            String lastName,
            Map<String, Object> metadata,
            String phone,
            int stampCount,
            String updatedAt,
            Map<String, Object> additionalProperties) {
        this.accountId = accountId;
        this.birthday = birthday;
        this.createdAt = createdAt;
        this.customerCards = customerCards;
        this.email = email;
        this.externalReferences = externalReferences;
        this.firstName = firstName;
        this.id = id;
        this.lastName = lastName;
        this.metadata = metadata;
        this.phone = phone;
        this.stampCount = stampCount;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Parent store ID
     */
    @JsonProperty("account_id")
    public int getAccountId() {
        return accountId;
    }

    /**
     * @return Birthday as YYYY-MM-DD
     */
    @JsonProperty("birthday")
    public String getBirthday() {
        return birthday;
    }

    /**
     * @return ISO 8601 creation timestamp
     */
    @JsonProperty("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Cards this customer is enrolled on
     */
    @JsonProperty("customer_cards")
    public List<String> getCustomerCards() {
        return customerCards;
    }

    /**
     * @return Email address, unique per store
     */
    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    /**
     * @return Links to records in other systems
     */
    @JsonProperty("external_references")
    public List<String> getExternalReferences() {
        return externalReferences;
    }

    /**
     * @return First name
     */
    @JsonProperty("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * @return Unique customer ID
     */
    @JsonProperty("id")
    public int getId() {
        return id;
    }

    /**
     * @return Last name
     */
    @JsonProperty("last_name")
    public String getLastName() {
        return lastName;
    }

    /**
     * @return Free form per customer data
     */
    @JsonProperty("metadata")
    public Map<String, Object> getMetadata() {
        return metadata;
    }

    /**
     * @return Phone number, unique per store
     */
    @JsonProperty("phone")
    public String getPhone() {
        return phone;
    }

    /**
     * @return Total stamps across every card
     */
    @JsonProperty("stamp_count")
    public int getStampCount() {
        return stampCount;
    }

    /**
     * @return ISO 8601 last-update timestamp
     */
    @JsonProperty("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetCustomersResponse && equalTo((GetCustomersResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetCustomersResponse other) {
        return accountId == other.accountId
                && birthday.equals(other.birthday)
                && createdAt.equals(other.createdAt)
                && customerCards.equals(other.customerCards)
                && email.equals(other.email)
                && externalReferences.equals(other.externalReferences)
                && firstName.equals(other.firstName)
                && id == other.id
                && lastName.equals(other.lastName)
                && metadata.equals(other.metadata)
                && phone.equals(other.phone)
                && stampCount == other.stampCount
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.accountId,
                this.birthday,
                this.createdAt,
                this.customerCards,
                this.email,
                this.externalReferences,
                this.firstName,
                this.id,
                this.lastName,
                this.metadata,
                this.phone,
                this.stampCount,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccountIdStage builder() {
        return new Builder();
    }

    public interface AccountIdStage {
        /**
         * <p>Parent store ID</p>
         */
        BirthdayStage accountId(int accountId);

        Builder from(GetCustomersResponse other);
    }

    public interface BirthdayStage {
        /**
         * <p>Birthday as YYYY-MM-DD</p>
         */
        CreatedAtStage birthday(@NotNull String birthday);
    }

    public interface CreatedAtStage {
        /**
         * <p>ISO 8601 creation timestamp</p>
         */
        EmailStage createdAt(@NotNull String createdAt);
    }

    public interface EmailStage {
        /**
         * <p>Email address, unique per store</p>
         */
        FirstNameStage email(@NotNull String email);
    }

    public interface FirstNameStage {
        /**
         * <p>First name</p>
         */
        IdStage firstName(@NotNull String firstName);
    }

    public interface IdStage {
        /**
         * <p>Unique customer ID</p>
         */
        LastNameStage id(int id);
    }

    public interface LastNameStage {
        /**
         * <p>Last name</p>
         */
        PhoneStage lastName(@NotNull String lastName);
    }

    public interface PhoneStage {
        /**
         * <p>Phone number, unique per store</p>
         */
        StampCountStage phone(@NotNull String phone);
    }

    public interface StampCountStage {
        /**
         * <p>Total stamps across every card</p>
         */
        UpdatedAtStage stampCount(int stampCount);
    }

    public interface UpdatedAtStage {
        /**
         * <p>ISO 8601 last-update timestamp</p>
         */
        _FinalStage updatedAt(@NotNull String updatedAt);
    }

    public interface _FinalStage {
        GetCustomersResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Cards this customer is enrolled on</p>
         */
        _FinalStage customerCards(List<String> customerCards);

        _FinalStage addCustomerCards(String customerCards);

        _FinalStage addAllCustomerCards(List<String> customerCards);

        /**
         * <p>Links to records in other systems</p>
         */
        _FinalStage externalReferences(List<String> externalReferences);

        _FinalStage addExternalReferences(String externalReferences);

        _FinalStage addAllExternalReferences(List<String> externalReferences);

        /**
         * <p>Free form per customer data</p>
         */
        _FinalStage metadata(Map<String, Object> metadata);

        _FinalStage putAllMetadata(Map<String, Object> metadata);

        _FinalStage metadata(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AccountIdStage,
                    BirthdayStage,
                    CreatedAtStage,
                    EmailStage,
                    FirstNameStage,
                    IdStage,
                    LastNameStage,
                    PhoneStage,
                    StampCountStage,
                    UpdatedAtStage,
                    _FinalStage {
        private int accountId;

        private String birthday;

        private String createdAt;

        private String email;

        private String firstName;

        private int id;

        private String lastName;

        private String phone;

        private int stampCount;

        private String updatedAt;

        private Map<String, Object> metadata = new LinkedHashMap<>();

        private List<String> externalReferences = new ArrayList<>();

        private List<String> customerCards = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetCustomersResponse other) {
            accountId(other.getAccountId());
            birthday(other.getBirthday());
            createdAt(other.getCreatedAt());
            customerCards(other.getCustomerCards());
            email(other.getEmail());
            externalReferences(other.getExternalReferences());
            firstName(other.getFirstName());
            id(other.getId());
            lastName(other.getLastName());
            metadata(other.getMetadata());
            phone(other.getPhone());
            stampCount(other.getStampCount());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>Parent store ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("account_id")
        public BirthdayStage accountId(int accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * <p>Birthday as YYYY-MM-DD</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("birthday")
        public CreatedAtStage birthday(@NotNull String birthday) {
            this.birthday = Objects.requireNonNull(birthday, "birthday must not be null");
            return this;
        }

        /**
         * <p>ISO 8601 creation timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public EmailStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Email address, unique per store</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("email")
        public FirstNameStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * <p>First name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("first_name")
        public IdStage firstName(@NotNull String firstName) {
            this.firstName = Objects.requireNonNull(firstName, "firstName must not be null");
            return this;
        }

        /**
         * <p>Unique customer ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public LastNameStage id(int id) {
            this.id = id;
            return this;
        }

        /**
         * <p>Last name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("last_name")
        public PhoneStage lastName(@NotNull String lastName) {
            this.lastName = Objects.requireNonNull(lastName, "lastName must not be null");
            return this;
        }

        /**
         * <p>Phone number, unique per store</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("phone")
        public StampCountStage phone(@NotNull String phone) {
            this.phone = Objects.requireNonNull(phone, "phone must not be null");
            return this;
        }

        /**
         * <p>Total stamps across every card</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stamp_count")
        public UpdatedAtStage stampCount(int stampCount) {
            this.stampCount = stampCount;
            return this;
        }

        /**
         * <p>ISO 8601 last-update timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Free form per customer data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(String key, Object value) {
            this.metadata.put(key, value);
            return this;
        }

        /**
         * <p>Free form per customer data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllMetadata(Map<String, Object> metadata) {
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>Free form per customer data</p>
         */
        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Map<String, Object> metadata) {
            this.metadata.clear();
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>Links to records in other systems</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllExternalReferences(List<String> externalReferences) {
            if (externalReferences != null) {
                this.externalReferences.addAll(externalReferences);
            }
            return this;
        }

        /**
         * <p>Links to records in other systems</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addExternalReferences(String externalReferences) {
            this.externalReferences.add(externalReferences);
            return this;
        }

        /**
         * <p>Links to records in other systems</p>
         */
        @java.lang.Override
        @JsonSetter(value = "external_references", nulls = Nulls.SKIP)
        public _FinalStage externalReferences(List<String> externalReferences) {
            this.externalReferences.clear();
            if (externalReferences != null) {
                this.externalReferences.addAll(externalReferences);
            }
            return this;
        }

        /**
         * <p>Cards this customer is enrolled on</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllCustomerCards(List<String> customerCards) {
            if (customerCards != null) {
                this.customerCards.addAll(customerCards);
            }
            return this;
        }

        /**
         * <p>Cards this customer is enrolled on</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addCustomerCards(String customerCards) {
            this.customerCards.add(customerCards);
            return this;
        }

        /**
         * <p>Cards this customer is enrolled on</p>
         */
        @java.lang.Override
        @JsonSetter(value = "customer_cards", nulls = Nulls.SKIP)
        public _FinalStage customerCards(List<String> customerCards) {
            this.customerCards.clear();
            if (customerCards != null) {
                this.customerCards.addAll(customerCards);
            }
            return this;
        }

        @java.lang.Override
        public GetCustomersResponse build() {
            return new GetCustomersResponse(
                    accountId,
                    birthday,
                    createdAt,
                    customerCards,
                    email,
                    externalReferences,
                    firstName,
                    id,
                    lastName,
                    metadata,
                    phone,
                    stampCount,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
