/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customers.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateCustomersRequestCustomer.Builder.class)
public final class UpdateCustomersRequestCustomer {
    private final Optional<String> birthday;

    private final Optional<String> email;

    private final Optional<List<String>> externalReferences;

    private final Optional<String> firstName;

    private final Optional<String> lastName;

    private final Optional<Map<String, Object>> metadata;

    private final Optional<String> phone;

    private final Map<String, Object> additionalProperties;

    private UpdateCustomersRequestCustomer(
            Optional<String> birthday,
            Optional<String> email,
            Optional<List<String>> externalReferences,
            Optional<String> firstName,
            Optional<String> lastName,
            Optional<Map<String, Object>> metadata,
            Optional<String> phone,
            Map<String, Object> additionalProperties) {
        this.birthday = birthday;
        this.email = email;
        this.externalReferences = externalReferences;
        this.firstName = firstName;
        this.lastName = lastName;
        this.metadata = metadata;
        this.phone = phone;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Customer's birthday (YYYY-MM-DD)
     */
    @JsonProperty("birthday")
    public Optional<String> getBirthday() {
        return birthday;
    }

    /**
     * @return Customer's email address (unique per store)
     */
    @JsonProperty("email")
    public Optional<String> getEmail() {
        return email;
    }

    /**
     * @return Array of <code>{source, external_id, metadata}</code> objects to upsert
     */
    @JsonProperty("external_references")
    public Optional<List<String>> getExternalReferences() {
        return externalReferences;
    }

    /**
     * @return Customer's first name
     */
    @JsonProperty("first_name")
    public Optional<String> getFirstName() {
        return firstName;
    }

    /**
     * @return Customer's last name
     */
    @JsonProperty("last_name")
    public Optional<String> getLastName() {
        return lastName;
    }

    /**
     * @return Shallow-merged into existing metadata
     */
    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    /**
     * @return Customer's phone number (unique per store)
     */
    @JsonProperty("phone")
    public Optional<String> getPhone() {
        return phone;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateCustomersRequestCustomer && equalTo((UpdateCustomersRequestCustomer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateCustomersRequestCustomer other) {
        return birthday.equals(other.birthday)
                && email.equals(other.email)
                && externalReferences.equals(other.externalReferences)
                && firstName.equals(other.firstName)
                && lastName.equals(other.lastName)
                && metadata.equals(other.metadata)
                && phone.equals(other.phone);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.birthday,
                this.email,
                this.externalReferences,
                this.firstName,
                this.lastName,
                this.metadata,
                this.phone);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> birthday = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<List<String>> externalReferences = Optional.empty();

        private Optional<String> firstName = Optional.empty();

        private Optional<String> lastName = Optional.empty();

        private Optional<Map<String, Object>> metadata = Optional.empty();

        private Optional<String> phone = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateCustomersRequestCustomer other) {
            birthday(other.getBirthday());
            email(other.getEmail());
            externalReferences(other.getExternalReferences());
            firstName(other.getFirstName());
            lastName(other.getLastName());
            metadata(other.getMetadata());
            phone(other.getPhone());
            return this;
        }

        /**
         * <p>Customer's birthday (YYYY-MM-DD)</p>
         */
        @JsonSetter(value = "birthday", nulls = Nulls.SKIP)
        public Builder birthday(Optional<String> birthday) {
            this.birthday = birthday;
            return this;
        }

        public Builder birthday(String birthday) {
            this.birthday = Optional.ofNullable(birthday);
            return this;
        }

        /**
         * <p>Customer's email address (unique per store)</p>
         */
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public Builder email(Optional<String> email) {
            this.email = email;
            return this;
        }

        public Builder email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Array of <code>{source, external_id, metadata}</code> objects to upsert</p>
         */
        @JsonSetter(value = "external_references", nulls = Nulls.SKIP)
        public Builder externalReferences(Optional<List<String>> externalReferences) {
            this.externalReferences = externalReferences;
            return this;
        }

        public Builder externalReferences(List<String> externalReferences) {
            this.externalReferences = Optional.ofNullable(externalReferences);
            return this;
        }

        /**
         * <p>Customer's first name</p>
         */
        @JsonSetter(value = "first_name", nulls = Nulls.SKIP)
        public Builder firstName(Optional<String> firstName) {
            this.firstName = firstName;
            return this;
        }

        public Builder firstName(String firstName) {
            this.firstName = Optional.ofNullable(firstName);
            return this;
        }

        /**
         * <p>Customer's last name</p>
         */
        @JsonSetter(value = "last_name", nulls = Nulls.SKIP)
        public Builder lastName(Optional<String> lastName) {
            this.lastName = lastName;
            return this;
        }

        public Builder lastName(String lastName) {
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        /**
         * <p>Shallow-merged into existing metadata</p>
         */
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * <p>Customer's phone number (unique per store)</p>
         */
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public Builder phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        public Builder phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        public UpdateCustomersRequestCustomer build() {
            return new UpdateCustomersRequestCustomer(
                    birthday, email, externalReferences, firstName, lastName, metadata, phone, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
