/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customercards.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RedeemCustomerCardsRequest.Builder.class)
public final class RedeemCustomerCardsRequest {
    private final int rewardId;

    private final Map<String, Object> additionalProperties;

    private RedeemCustomerCardsRequest(int rewardId, Map<String, Object> additionalProperties) {
        this.rewardId = rewardId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Reward ID to redeem
     */
    @JsonProperty("reward_id")
    public int getRewardId() {
        return rewardId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RedeemCustomerCardsRequest && equalTo((RedeemCustomerCardsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RedeemCustomerCardsRequest other) {
        return rewardId == other.rewardId;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.rewardId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RewardIdStage builder() {
        return new Builder();
    }

    public interface RewardIdStage {
        /**
         * <p>Reward ID to redeem</p>
         */
        _FinalStage rewardId(int rewardId);

        Builder from(RedeemCustomerCardsRequest other);
    }

    public interface _FinalStage {
        RedeemCustomerCardsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RewardIdStage, _FinalStage {
        private int rewardId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RedeemCustomerCardsRequest other) {
            rewardId(other.getRewardId());
            return this;
        }

        /**
         * <p>Reward ID to redeem</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reward_id")
        public _FinalStage rewardId(int rewardId) {
            this.rewardId = rewardId;
            return this;
        }

        @java.lang.Override
        public RedeemCustomerCardsRequest build() {
            return new RedeemCustomerCardsRequest(rewardId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
