/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customercards.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StampCustomerCardsRequest.Builder.class)
public final class StampCustomerCardsRequest {
    private final Optional<Boolean> skipNotifications;

    private final int stamps;

    private final Map<String, Object> additionalProperties;

    private StampCustomerCardsRequest(
            Optional<Boolean> skipNotifications, int stamps, Map<String, Object> additionalProperties) {
        this.skipNotifications = skipNotifications;
        this.stamps = stamps;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return When true, stamp changes bypass notifications
     */
    @JsonProperty("skip_notifications")
    public Optional<Boolean> getSkipNotifications() {
        return skipNotifications;
    }

    /**
     * @return Number of stamps to add (e.g. 1, 3)
     */
    @JsonProperty("stamps")
    public int getStamps() {
        return stamps;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StampCustomerCardsRequest && equalTo((StampCustomerCardsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StampCustomerCardsRequest other) {
        return skipNotifications.equals(other.skipNotifications) && stamps == other.stamps;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.skipNotifications, this.stamps);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StampsStage builder() {
        return new Builder();
    }

    public interface StampsStage {
        /**
         * <p>Number of stamps to add (e.g. 1, 3)</p>
         */
        _FinalStage stamps(int stamps);

        Builder from(StampCustomerCardsRequest other);
    }

    public interface _FinalStage {
        StampCustomerCardsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>When true, stamp changes bypass notifications</p>
         */
        _FinalStage skipNotifications(Optional<Boolean> skipNotifications);

        _FinalStage skipNotifications(Boolean skipNotifications);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StampsStage, _FinalStage {
        private int stamps;

        private Optional<Boolean> skipNotifications = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(StampCustomerCardsRequest other) {
            skipNotifications(other.getSkipNotifications());
            stamps(other.getStamps());
            return this;
        }

        /**
         * <p>Number of stamps to add (e.g. 1, 3)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stamps")
        public _FinalStage stamps(int stamps) {
            this.stamps = stamps;
            return this;
        }

        /**
         * <p>When true, stamp changes bypass notifications</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage skipNotifications(Boolean skipNotifications) {
            this.skipNotifications = Optional.ofNullable(skipNotifications);
            return this;
        }

        /**
         * <p>When true, stamp changes bypass notifications</p>
         */
        @java.lang.Override
        @JsonSetter(value = "skip_notifications", nulls = Nulls.SKIP)
        public _FinalStage skipNotifications(Optional<Boolean> skipNotifications) {
            this.skipNotifications = skipNotifications;
            return this;
        }

        @java.lang.Override
        public StampCustomerCardsRequest build() {
            return new StampCustomerCardsRequest(skipNotifications, stamps, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
