/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.errors;

import com.getleal.api.core.LealApiException;
import com.getleal.api.types.Error;
import okhttp3.Response;

public final class GoneError extends LealApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Error body;

    public GoneError(Error body) {
        super("GoneError", 410, body);
        this.body = body;
    }

    public GoneError(Error body, Response rawResponse) {
        super("GoneError", 410, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Error body() {
        return this.body;
    }
}
