/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.rewards;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.rewards.requests.CreateRewardsRequest;
import com.getleal.api.resources.rewards.requests.DeleteRewardsRequest;
import com.getleal.api.resources.rewards.requests.GetRewardsRequest;
import com.getleal.api.resources.rewards.requests.ListRewardsRequest;
import com.getleal.api.resources.rewards.requests.UpdateRewardsRequest;
import com.getleal.api.resources.rewards.types.CreateRewardsResponse;
import com.getleal.api.resources.rewards.types.GetRewardsResponse;
import com.getleal.api.resources.rewards.types.ListRewardsResponseItem;
import com.getleal.api.resources.rewards.types.UpdateRewardsResponse;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncRewardsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRewardsClient rawClient;

    public AsyncRewardsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRewardsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRewardsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public CompletableFuture<List<ListRewardsResponseItem>> list(int accountId) {
        return this.rawClient.list(accountId).thenApply(response -> response.body());
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public CompletableFuture<List<ListRewardsResponseItem>> list(int accountId, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public CompletableFuture<List<ListRewardsResponseItem>> list(int accountId, ListRewardsRequest request) {
        return this.rawClient.list(accountId, request).thenApply(response -> response.body());
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public CompletableFuture<List<ListRewardsResponseItem>> list(
            int accountId, ListRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Creates a new reward for a loyalty card. The card must belong to the same store.
     * The <code>card_id</code> is required on create but cannot be changed afterwards.
     */
    public CompletableFuture<CreateRewardsResponse> create(int accountId, CreateRewardsRequest request) {
        return this.rawClient.create(accountId, request).thenApply(response -> response.body());
    }

    /**
     * Creates a new reward for a loyalty card. The card must belong to the same store.
     * The <code>card_id</code> is required on create but cannot be changed afterwards.
     */
    public CompletableFuture<CreateRewardsResponse> create(
            int accountId, CreateRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(accountId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single reward by ID.
     */
    public CompletableFuture<GetRewardsResponse> get(int accountId, int id) {
        return this.rawClient.get(accountId, id).thenApply(response -> response.body());
    }

    /**
     * Returns a single reward by ID.
     */
    public CompletableFuture<GetRewardsResponse> get(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single reward by ID.
     */
    public CompletableFuture<GetRewardsResponse> get(int accountId, int id, GetRewardsRequest request) {
        return this.rawClient.get(accountId, id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a single reward by ID.
     */
    public CompletableFuture<GetRewardsResponse> get(
            int accountId, int id, GetRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public CompletableFuture<Void> delete(int accountId, int id) {
        return this.rawClient.delete(accountId, id).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public CompletableFuture<Void> delete(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.delete(accountId, id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public CompletableFuture<Void> delete(int accountId, int id, DeleteRewardsRequest request) {
        return this.rawClient.delete(accountId, id, request).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public CompletableFuture<Void> delete(
            int accountId, int id, DeleteRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(accountId, id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates an existing reward. The <code>card_id</code> cannot be changed after creation.
     */
    public CompletableFuture<UpdateRewardsResponse> update(int accountId, int id, UpdateRewardsRequest request) {
        return this.rawClient.update(accountId, id, request).thenApply(response -> response.body());
    }

    /**
     * Updates an existing reward. The <code>card_id</code> cannot be changed after creation.
     */
    public CompletableFuture<UpdateRewardsResponse> update(
            int accountId, int id, UpdateRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(accountId, id, request, requestOptions).thenApply(response -> response.body());
    }
}
