/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.rewards;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.rewards.requests.CreateRewardsRequest;
import com.getleal.api.resources.rewards.requests.DeleteRewardsRequest;
import com.getleal.api.resources.rewards.requests.GetRewardsRequest;
import com.getleal.api.resources.rewards.requests.ListRewardsRequest;
import com.getleal.api.resources.rewards.requests.UpdateRewardsRequest;
import com.getleal.api.resources.rewards.types.CreateRewardsResponse;
import com.getleal.api.resources.rewards.types.GetRewardsResponse;
import com.getleal.api.resources.rewards.types.ListRewardsResponseItem;
import com.getleal.api.resources.rewards.types.UpdateRewardsResponse;
import java.util.List;

public class RewardsClient {
    protected final ClientOptions clientOptions;

    private final RawRewardsClient rawClient;

    public RewardsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRewardsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRewardsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public List<ListRewardsResponseItem> list(int accountId) {
        return this.rawClient.list(accountId).body();
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public List<ListRewardsResponseItem> list(int accountId, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, requestOptions).body();
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public List<ListRewardsResponseItem> list(int accountId, ListRewardsRequest request) {
        return this.rawClient.list(accountId, request).body();
    }

    /**
     * Returns all rewards for the store. Optionally filter by card or active status.
     */
    public List<ListRewardsResponseItem> list(
            int accountId, ListRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, request, requestOptions).body();
    }

    /**
     * Creates a new reward for a loyalty card. The card must belong to the same store.
     * The <code>card_id</code> is required on create but cannot be changed afterwards.
     */
    public CreateRewardsResponse create(int accountId, CreateRewardsRequest request) {
        return this.rawClient.create(accountId, request).body();
    }

    /**
     * Creates a new reward for a loyalty card. The card must belong to the same store.
     * The <code>card_id</code> is required on create but cannot be changed afterwards.
     */
    public CreateRewardsResponse create(int accountId, CreateRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(accountId, request, requestOptions).body();
    }

    /**
     * Returns a single reward by ID.
     */
    public GetRewardsResponse get(int accountId, int id) {
        return this.rawClient.get(accountId, id).body();
    }

    /**
     * Returns a single reward by ID.
     */
    public GetRewardsResponse get(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, requestOptions).body();
    }

    /**
     * Returns a single reward by ID.
     */
    public GetRewardsResponse get(int accountId, int id, GetRewardsRequest request) {
        return this.rawClient.get(accountId, id, request).body();
    }

    /**
     * Returns a single reward by ID.
     */
    public GetRewardsResponse get(int accountId, int id, GetRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, request, requestOptions).body();
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public void delete(int accountId, int id) {
        this.rawClient.delete(accountId, id).body();
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public void delete(int accountId, int id, RequestOptions requestOptions) {
        this.rawClient.delete(accountId, id, requestOptions).body();
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public void delete(int accountId, int id, DeleteRewardsRequest request) {
        this.rawClient.delete(accountId, id, request).body();
    }

    /**
     * Permanently deletes a reward. This cannot be undone.
     */
    public void delete(int accountId, int id, DeleteRewardsRequest request, RequestOptions requestOptions) {
        this.rawClient.delete(accountId, id, request, requestOptions).body();
    }

    /**
     * Updates an existing reward. The <code>card_id</code> cannot be changed after creation.
     */
    public UpdateRewardsResponse update(int accountId, int id, UpdateRewardsRequest request) {
        return this.rawClient.update(accountId, id, request).body();
    }

    /**
     * Updates an existing reward. The <code>card_id</code> cannot be changed after creation.
     */
    public UpdateRewardsResponse update(
            int accountId, int id, UpdateRewardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(accountId, id, request, requestOptions).body();
    }
}
