/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.cards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateCardsRequestCard.Builder.class)
public final class CreateCardsRequestCard {
    private final Optional<List<String>> auxiliaryFields;

    private final Optional<String> cardColor;

    private final Optional<String> expiresAt;

    private final Optional<String> headerText;

    private final Optional<Integer> initialStamps;

    private final String name;

    private final Optional<Boolean> showMemberField;

    private final Optional<Boolean> showStampsToRewardField;

    private final Optional<String> stampBackgroundColor;

    private final Optional<String> stampColor;

    private final Optional<String> stampIcon;

    private final Optional<Integer> stampsRequired;

    private final Optional<String> stripColor;

    private final Optional<String> stripPreset;

    private final Optional<String> stripType;

    private final Optional<String> textColor;

    private final Map<String, Object> additionalProperties;

    private CreateCardsRequestCard(
            Optional<List<String>> auxiliaryFields,
            Optional<String> cardColor,
            Optional<String> expiresAt,
            Optional<String> headerText,
            Optional<Integer> initialStamps,
            String name,
            Optional<Boolean> showMemberField,
            Optional<Boolean> showStampsToRewardField,
            Optional<String> stampBackgroundColor,
            Optional<String> stampColor,
            Optional<String> stampIcon,
            Optional<Integer> stampsRequired,
            Optional<String> stripColor,
            Optional<String> stripPreset,
            Optional<String> stripType,
            Optional<String> textColor,
            Map<String, Object> additionalProperties) {
        this.auxiliaryFields = auxiliaryFields;
        this.cardColor = cardColor;
        this.expiresAt = expiresAt;
        this.headerText = headerText;
        this.initialStamps = initialStamps;
        this.name = name;
        this.showMemberField = showMemberField;
        this.showStampsToRewardField = showStampsToRewardField;
        this.stampBackgroundColor = stampBackgroundColor;
        this.stampColor = stampColor;
        this.stampIcon = stampIcon;
        this.stampsRequired = stampsRequired;
        this.stripColor = stripColor;
        this.stripPreset = stripPreset;
        this.stripType = stripType;
        this.textColor = textColor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Up to two extra front-of-pass fields. Blank values are ignored.
     */
    @JsonProperty("auxiliary_fields")
    public Optional<List<String>> getAuxiliaryFields() {
        return auxiliaryFields;
    }

    /**
     * @return Hex colour for the card background (e.g. '#6B4226')
     */
    @JsonProperty("card_color")
    public Optional<String> getCardColor() {
        return cardColor;
    }

    /**
     * @return Card expiry timestamp (ISO 8601)
     */
    @JsonProperty("expires_at")
    public Optional<String> getExpiresAt() {
        return expiresAt;
    }

    /**
     * @return Optional header text displayed on the card
     */
    @JsonProperty("header_text")
    public Optional<String> getHeaderText() {
        return headerText;
    }

    /**
     * @return Number of stamps pre-filled on new customer cards (must be &gt;= 0 and &lt; stamps_required)
     */
    @JsonProperty("initial_stamps")
    public Optional<Integer> getInitialStamps() {
        return initialStamps;
    }

    /**
     * @return Card name (e.g. 'Coffee Loyalty Card')
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Whether wallet passes show the member name field
     */
    @JsonProperty("show_member_field")
    public Optional<Boolean> getShowMemberField() {
        return showMemberField;
    }

    /**
     * @return Whether wallet passes show the stamps-to-reward field
     */
    @JsonProperty("show_stamps_to_reward_field")
    public Optional<Boolean> getShowStampsToRewardField() {
        return showStampsToRewardField;
    }

    /**
     * @return Hex colour for stamp backgrounds
     */
    @JsonProperty("stamp_background_color")
    public Optional<String> getStampBackgroundColor() {
        return stampBackgroundColor;
    }

    /**
     * @return Hex colour for stamp icons
     */
    @JsonProperty("stamp_color")
    public Optional<String> getStampColor() {
        return stampColor;
    }

    /**
     * @return Stamp icon identifier
     */
    @JsonProperty("stamp_icon")
    public Optional<String> getStampIcon() {
        return stampIcon;
    }

    /**
     * @return Number of stamps needed to complete the card (1–21)
     */
    @JsonProperty("stamps_required")
    public Optional<Integer> getStampsRequired() {
        return stampsRequired;
    }

    /**
     * @return Hex colour for the strip (used when strip_type is 'color')
     */
    @JsonProperty("strip_color")
    public Optional<String> getStripColor() {
        return stripColor;
    }

    /**
     * @return Preset strip image identifier (used when strip_type is 'preset')
     */
    @JsonProperty("strip_preset")
    public Optional<String> getStripPreset() {
        return stripPreset;
    }

    /**
     * @return Strip image type
     */
    @JsonProperty("strip_type")
    public Optional<String> getStripType() {
        return stripType;
    }

    /**
     * @return Hex colour for card text
     */
    @JsonProperty("text_color")
    public Optional<String> getTextColor() {
        return textColor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateCardsRequestCard && equalTo((CreateCardsRequestCard) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateCardsRequestCard other) {
        return auxiliaryFields.equals(other.auxiliaryFields)
                && cardColor.equals(other.cardColor)
                && expiresAt.equals(other.expiresAt)
                && headerText.equals(other.headerText)
                && initialStamps.equals(other.initialStamps)
                && name.equals(other.name)
                && showMemberField.equals(other.showMemberField)
                && showStampsToRewardField.equals(other.showStampsToRewardField)
                && stampBackgroundColor.equals(other.stampBackgroundColor)
                && stampColor.equals(other.stampColor)
                && stampIcon.equals(other.stampIcon)
                && stampsRequired.equals(other.stampsRequired)
                && stripColor.equals(other.stripColor)
                && stripPreset.equals(other.stripPreset)
                && stripType.equals(other.stripType)
                && textColor.equals(other.textColor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.auxiliaryFields,
                this.cardColor,
                this.expiresAt,
                this.headerText,
                this.initialStamps,
                this.name,
                this.showMemberField,
                this.showStampsToRewardField,
                this.stampBackgroundColor,
                this.stampColor,
                this.stampIcon,
                this.stampsRequired,
                this.stripColor,
                this.stripPreset,
                this.stripType,
                this.textColor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Card name (e.g. 'Coffee Loyalty Card')</p>
         */
        _FinalStage name(@NotNull String name);

        Builder from(CreateCardsRequestCard other);
    }

    public interface _FinalStage {
        CreateCardsRequestCard build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Up to two extra front-of-pass fields. Blank values are ignored.</p>
         */
        _FinalStage auxiliaryFields(Optional<List<String>> auxiliaryFields);

        _FinalStage auxiliaryFields(List<String> auxiliaryFields);

        /**
         * <p>Hex colour for the card background (e.g. '#6B4226')</p>
         */
        _FinalStage cardColor(Optional<String> cardColor);

        _FinalStage cardColor(String cardColor);

        /**
         * <p>Card expiry timestamp (ISO 8601)</p>
         */
        _FinalStage expiresAt(Optional<String> expiresAt);

        _FinalStage expiresAt(String expiresAt);

        /**
         * <p>Optional header text displayed on the card</p>
         */
        _FinalStage headerText(Optional<String> headerText);

        _FinalStage headerText(String headerText);

        /**
         * <p>Number of stamps pre-filled on new customer cards (must be &gt;= 0 and &lt; stamps_required)</p>
         */
        _FinalStage initialStamps(Optional<Integer> initialStamps);

        _FinalStage initialStamps(Integer initialStamps);

        /**
         * <p>Whether wallet passes show the member name field</p>
         */
        _FinalStage showMemberField(Optional<Boolean> showMemberField);

        _FinalStage showMemberField(Boolean showMemberField);

        /**
         * <p>Whether wallet passes show the stamps-to-reward field</p>
         */
        _FinalStage showStampsToRewardField(Optional<Boolean> showStampsToRewardField);

        _FinalStage showStampsToRewardField(Boolean showStampsToRewardField);

        /**
         * <p>Hex colour for stamp backgrounds</p>
         */
        _FinalStage stampBackgroundColor(Optional<String> stampBackgroundColor);

        _FinalStage stampBackgroundColor(String stampBackgroundColor);

        /**
         * <p>Hex colour for stamp icons</p>
         */
        _FinalStage stampColor(Optional<String> stampColor);

        _FinalStage stampColor(String stampColor);

        /**
         * <p>Stamp icon identifier</p>
         */
        _FinalStage stampIcon(Optional<String> stampIcon);

        _FinalStage stampIcon(String stampIcon);

        /**
         * <p>Number of stamps needed to complete the card (1–21)</p>
         */
        _FinalStage stampsRequired(Optional<Integer> stampsRequired);

        _FinalStage stampsRequired(Integer stampsRequired);

        /**
         * <p>Hex colour for the strip (used when strip_type is 'color')</p>
         */
        _FinalStage stripColor(Optional<String> stripColor);

        _FinalStage stripColor(String stripColor);

        /**
         * <p>Preset strip image identifier (used when strip_type is 'preset')</p>
         */
        _FinalStage stripPreset(Optional<String> stripPreset);

        _FinalStage stripPreset(String stripPreset);

        /**
         * <p>Strip image type</p>
         */
        _FinalStage stripType(Optional<String> stripType);

        _FinalStage stripType(String stripType);

        /**
         * <p>Hex colour for card text</p>
         */
        _FinalStage textColor(Optional<String> textColor);

        _FinalStage textColor(String textColor);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Optional<String> textColor = Optional.empty();

        private Optional<String> stripType = Optional.empty();

        private Optional<String> stripPreset = Optional.empty();

        private Optional<String> stripColor = Optional.empty();

        private Optional<Integer> stampsRequired = Optional.empty();

        private Optional<String> stampIcon = Optional.empty();

        private Optional<String> stampColor = Optional.empty();

        private Optional<String> stampBackgroundColor = Optional.empty();

        private Optional<Boolean> showStampsToRewardField = Optional.empty();

        private Optional<Boolean> showMemberField = Optional.empty();

        private Optional<Integer> initialStamps = Optional.empty();

        private Optional<String> headerText = Optional.empty();

        private Optional<String> expiresAt = Optional.empty();

        private Optional<String> cardColor = Optional.empty();

        private Optional<List<String>> auxiliaryFields = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateCardsRequestCard other) {
            auxiliaryFields(other.getAuxiliaryFields());
            cardColor(other.getCardColor());
            expiresAt(other.getExpiresAt());
            headerText(other.getHeaderText());
            initialStamps(other.getInitialStamps());
            name(other.getName());
            showMemberField(other.getShowMemberField());
            showStampsToRewardField(other.getShowStampsToRewardField());
            stampBackgroundColor(other.getStampBackgroundColor());
            stampColor(other.getStampColor());
            stampIcon(other.getStampIcon());
            stampsRequired(other.getStampsRequired());
            stripColor(other.getStripColor());
            stripPreset(other.getStripPreset());
            stripType(other.getStripType());
            textColor(other.getTextColor());
            return this;
        }

        /**
         * <p>Card name (e.g. 'Coffee Loyalty Card')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Hex colour for card text</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage textColor(String textColor) {
            this.textColor = Optional.ofNullable(textColor);
            return this;
        }

        /**
         * <p>Hex colour for card text</p>
         */
        @java.lang.Override
        @JsonSetter(value = "text_color", nulls = Nulls.SKIP)
        public _FinalStage textColor(Optional<String> textColor) {
            this.textColor = textColor;
            return this;
        }

        /**
         * <p>Strip image type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stripType(String stripType) {
            this.stripType = Optional.ofNullable(stripType);
            return this;
        }

        /**
         * <p>Strip image type</p>
         */
        @java.lang.Override
        @JsonSetter(value = "strip_type", nulls = Nulls.SKIP)
        public _FinalStage stripType(Optional<String> stripType) {
            this.stripType = stripType;
            return this;
        }

        /**
         * <p>Preset strip image identifier (used when strip_type is 'preset')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stripPreset(String stripPreset) {
            this.stripPreset = Optional.ofNullable(stripPreset);
            return this;
        }

        /**
         * <p>Preset strip image identifier (used when strip_type is 'preset')</p>
         */
        @java.lang.Override
        @JsonSetter(value = "strip_preset", nulls = Nulls.SKIP)
        public _FinalStage stripPreset(Optional<String> stripPreset) {
            this.stripPreset = stripPreset;
            return this;
        }

        /**
         * <p>Hex colour for the strip (used when strip_type is 'color')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stripColor(String stripColor) {
            this.stripColor = Optional.ofNullable(stripColor);
            return this;
        }

        /**
         * <p>Hex colour for the strip (used when strip_type is 'color')</p>
         */
        @java.lang.Override
        @JsonSetter(value = "strip_color", nulls = Nulls.SKIP)
        public _FinalStage stripColor(Optional<String> stripColor) {
            this.stripColor = stripColor;
            return this;
        }

        /**
         * <p>Number of stamps needed to complete the card (1–21)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stampsRequired(Integer stampsRequired) {
            this.stampsRequired = Optional.ofNullable(stampsRequired);
            return this;
        }

        /**
         * <p>Number of stamps needed to complete the card (1–21)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "stamps_required", nulls = Nulls.SKIP)
        public _FinalStage stampsRequired(Optional<Integer> stampsRequired) {
            this.stampsRequired = stampsRequired;
            return this;
        }

        /**
         * <p>Stamp icon identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stampIcon(String stampIcon) {
            this.stampIcon = Optional.ofNullable(stampIcon);
            return this;
        }

        /**
         * <p>Stamp icon identifier</p>
         */
        @java.lang.Override
        @JsonSetter(value = "stamp_icon", nulls = Nulls.SKIP)
        public _FinalStage stampIcon(Optional<String> stampIcon) {
            this.stampIcon = stampIcon;
            return this;
        }

        /**
         * <p>Hex colour for stamp icons</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stampColor(String stampColor) {
            this.stampColor = Optional.ofNullable(stampColor);
            return this;
        }

        /**
         * <p>Hex colour for stamp icons</p>
         */
        @java.lang.Override
        @JsonSetter(value = "stamp_color", nulls = Nulls.SKIP)
        public _FinalStage stampColor(Optional<String> stampColor) {
            this.stampColor = stampColor;
            return this;
        }

        /**
         * <p>Hex colour for stamp backgrounds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage stampBackgroundColor(String stampBackgroundColor) {
            this.stampBackgroundColor = Optional.ofNullable(stampBackgroundColor);
            return this;
        }

        /**
         * <p>Hex colour for stamp backgrounds</p>
         */
        @java.lang.Override
        @JsonSetter(value = "stamp_background_color", nulls = Nulls.SKIP)
        public _FinalStage stampBackgroundColor(Optional<String> stampBackgroundColor) {
            this.stampBackgroundColor = stampBackgroundColor;
            return this;
        }

        /**
         * <p>Whether wallet passes show the stamps-to-reward field</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage showStampsToRewardField(Boolean showStampsToRewardField) {
            this.showStampsToRewardField = Optional.ofNullable(showStampsToRewardField);
            return this;
        }

        /**
         * <p>Whether wallet passes show the stamps-to-reward field</p>
         */
        @java.lang.Override
        @JsonSetter(value = "show_stamps_to_reward_field", nulls = Nulls.SKIP)
        public _FinalStage showStampsToRewardField(Optional<Boolean> showStampsToRewardField) {
            this.showStampsToRewardField = showStampsToRewardField;
            return this;
        }

        /**
         * <p>Whether wallet passes show the member name field</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage showMemberField(Boolean showMemberField) {
            this.showMemberField = Optional.ofNullable(showMemberField);
            return this;
        }

        /**
         * <p>Whether wallet passes show the member name field</p>
         */
        @java.lang.Override
        @JsonSetter(value = "show_member_field", nulls = Nulls.SKIP)
        public _FinalStage showMemberField(Optional<Boolean> showMemberField) {
            this.showMemberField = showMemberField;
            return this;
        }

        /**
         * <p>Number of stamps pre-filled on new customer cards (must be &gt;= 0 and &lt; stamps_required)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage initialStamps(Integer initialStamps) {
            this.initialStamps = Optional.ofNullable(initialStamps);
            return this;
        }

        /**
         * <p>Number of stamps pre-filled on new customer cards (must be &gt;= 0 and &lt; stamps_required)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "initial_stamps", nulls = Nulls.SKIP)
        public _FinalStage initialStamps(Optional<Integer> initialStamps) {
            this.initialStamps = initialStamps;
            return this;
        }

        /**
         * <p>Optional header text displayed on the card</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage headerText(String headerText) {
            this.headerText = Optional.ofNullable(headerText);
            return this;
        }

        /**
         * <p>Optional header text displayed on the card</p>
         */
        @java.lang.Override
        @JsonSetter(value = "header_text", nulls = Nulls.SKIP)
        public _FinalStage headerText(Optional<String> headerText) {
            this.headerText = headerText;
            return this;
        }

        /**
         * <p>Card expiry timestamp (ISO 8601)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expiresAt(String expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        /**
         * <p>Card expiry timestamp (ISO 8601)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public _FinalStage expiresAt(Optional<String> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * <p>Hex colour for the card background (e.g. '#6B4226')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage cardColor(String cardColor) {
            this.cardColor = Optional.ofNullable(cardColor);
            return this;
        }

        /**
         * <p>Hex colour for the card background (e.g. '#6B4226')</p>
         */
        @java.lang.Override
        @JsonSetter(value = "card_color", nulls = Nulls.SKIP)
        public _FinalStage cardColor(Optional<String> cardColor) {
            this.cardColor = cardColor;
            return this;
        }

        /**
         * <p>Up to two extra front-of-pass fields. Blank values are ignored.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage auxiliaryFields(List<String> auxiliaryFields) {
            this.auxiliaryFields = Optional.ofNullable(auxiliaryFields);
            return this;
        }

        /**
         * <p>Up to two extra front-of-pass fields. Blank values are ignored.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "auxiliary_fields", nulls = Nulls.SKIP)
        public _FinalStage auxiliaryFields(Optional<List<String>> auxiliaryFields) {
            this.auxiliaryFields = auxiliaryFields;
            return this;
        }

        @java.lang.Override
        public CreateCardsRequestCard build() {
            return new CreateCardsRequestCard(
                    auxiliaryFields,
                    cardColor,
                    expiresAt,
                    headerText,
                    initialStamps,
                    name,
                    showMemberField,
                    showStampsToRewardField,
                    stampBackgroundColor,
                    stampColor,
                    stampIcon,
                    stampsRequired,
                    stripColor,
                    stripPreset,
                    stripType,
                    textColor,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
