/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.cards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateCardsRequestCard.Builder.class)
public final class UpdateCardsRequestCard {
    private final Optional<String> cardColor;

    private final Optional<String> headerText;

    private final Optional<Integer> initialStamps;

    private final Optional<String> name;

    private final Optional<String> stampBackgroundColor;

    private final Optional<String> stampColor;

    private final Optional<String> stampIcon;

    private final Optional<Integer> stampsRequired;

    private final Optional<String> stripColor;

    private final Optional<String> stripPreset;

    private final Optional<String> stripType;

    private final Optional<String> textColor;

    private final Map<String, Object> additionalProperties;

    private UpdateCardsRequestCard(
            Optional<String> cardColor,
            Optional<String> headerText,
            Optional<Integer> initialStamps,
            Optional<String> name,
            Optional<String> stampBackgroundColor,
            Optional<String> stampColor,
            Optional<String> stampIcon,
            Optional<Integer> stampsRequired,
            Optional<String> stripColor,
            Optional<String> stripPreset,
            Optional<String> stripType,
            Optional<String> textColor,
            Map<String, Object> additionalProperties) {
        this.cardColor = cardColor;
        this.headerText = headerText;
        this.initialStamps = initialStamps;
        this.name = name;
        this.stampBackgroundColor = stampBackgroundColor;
        this.stampColor = stampColor;
        this.stampIcon = stampIcon;
        this.stampsRequired = stampsRequired;
        this.stripColor = stripColor;
        this.stripPreset = stripPreset;
        this.stripType = stripType;
        this.textColor = textColor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Hex colour for the card background
     */
    @JsonProperty("card_color")
    public Optional<String> getCardColor() {
        return cardColor;
    }

    /**
     * @return Optional header text displayed on the card
     */
    @JsonProperty("header_text")
    public Optional<String> getHeaderText() {
        return headerText;
    }

    /**
     * @return Pre-filled stamps (must be &gt;= 0 and &lt; stamps_required)
     */
    @JsonProperty("initial_stamps")
    public Optional<Integer> getInitialStamps() {
        return initialStamps;
    }

    /**
     * @return Card name
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Hex colour for stamp backgrounds
     */
    @JsonProperty("stamp_background_color")
    public Optional<String> getStampBackgroundColor() {
        return stampBackgroundColor;
    }

    /**
     * @return Hex colour for stamp icons
     */
    @JsonProperty("stamp_color")
    public Optional<String> getStampColor() {
        return stampColor;
    }

    /**
     * @return Stamp icon identifier
     */
    @JsonProperty("stamp_icon")
    public Optional<String> getStampIcon() {
        return stampIcon;
    }

    /**
     * @return Number of stamps needed (1–21)
     */
    @JsonProperty("stamps_required")
    public Optional<Integer> getStampsRequired() {
        return stampsRequired;
    }

    /**
     * @return Hex colour for the strip
     */
    @JsonProperty("strip_color")
    public Optional<String> getStripColor() {
        return stripColor;
    }

    /**
     * @return Preset strip image identifier
     */
    @JsonProperty("strip_preset")
    public Optional<String> getStripPreset() {
        return stripPreset;
    }

    /**
     * @return Strip image type
     */
    @JsonProperty("strip_type")
    public Optional<String> getStripType() {
        return stripType;
    }

    /**
     * @return Hex colour for card text
     */
    @JsonProperty("text_color")
    public Optional<String> getTextColor() {
        return textColor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateCardsRequestCard && equalTo((UpdateCardsRequestCard) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateCardsRequestCard other) {
        return cardColor.equals(other.cardColor)
                && headerText.equals(other.headerText)
                && initialStamps.equals(other.initialStamps)
                && name.equals(other.name)
                && stampBackgroundColor.equals(other.stampBackgroundColor)
                && stampColor.equals(other.stampColor)
                && stampIcon.equals(other.stampIcon)
                && stampsRequired.equals(other.stampsRequired)
                && stripColor.equals(other.stripColor)
                && stripPreset.equals(other.stripPreset)
                && stripType.equals(other.stripType)
                && textColor.equals(other.textColor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.cardColor,
                this.headerText,
                this.initialStamps,
                this.name,
                this.stampBackgroundColor,
                this.stampColor,
                this.stampIcon,
                this.stampsRequired,
                this.stripColor,
                this.stripPreset,
                this.stripType,
                this.textColor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> cardColor = Optional.empty();

        private Optional<String> headerText = Optional.empty();

        private Optional<Integer> initialStamps = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> stampBackgroundColor = Optional.empty();

        private Optional<String> stampColor = Optional.empty();

        private Optional<String> stampIcon = Optional.empty();

        private Optional<Integer> stampsRequired = Optional.empty();

        private Optional<String> stripColor = Optional.empty();

        private Optional<String> stripPreset = Optional.empty();

        private Optional<String> stripType = Optional.empty();

        private Optional<String> textColor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateCardsRequestCard other) {
            cardColor(other.getCardColor());
            headerText(other.getHeaderText());
            initialStamps(other.getInitialStamps());
            name(other.getName());
            stampBackgroundColor(other.getStampBackgroundColor());
            stampColor(other.getStampColor());
            stampIcon(other.getStampIcon());
            stampsRequired(other.getStampsRequired());
            stripColor(other.getStripColor());
            stripPreset(other.getStripPreset());
            stripType(other.getStripType());
            textColor(other.getTextColor());
            return this;
        }

        /**
         * <p>Hex colour for the card background</p>
         */
        @JsonSetter(value = "card_color", nulls = Nulls.SKIP)
        public Builder cardColor(Optional<String> cardColor) {
            this.cardColor = cardColor;
            return this;
        }

        public Builder cardColor(String cardColor) {
            this.cardColor = Optional.ofNullable(cardColor);
            return this;
        }

        /**
         * <p>Optional header text displayed on the card</p>
         */
        @JsonSetter(value = "header_text", nulls = Nulls.SKIP)
        public Builder headerText(Optional<String> headerText) {
            this.headerText = headerText;
            return this;
        }

        public Builder headerText(String headerText) {
            this.headerText = Optional.ofNullable(headerText);
            return this;
        }

        /**
         * <p>Pre-filled stamps (must be &gt;= 0 and &lt; stamps_required)</p>
         */
        @JsonSetter(value = "initial_stamps", nulls = Nulls.SKIP)
        public Builder initialStamps(Optional<Integer> initialStamps) {
            this.initialStamps = initialStamps;
            return this;
        }

        public Builder initialStamps(Integer initialStamps) {
            this.initialStamps = Optional.ofNullable(initialStamps);
            return this;
        }

        /**
         * <p>Card name</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Hex colour for stamp backgrounds</p>
         */
        @JsonSetter(value = "stamp_background_color", nulls = Nulls.SKIP)
        public Builder stampBackgroundColor(Optional<String> stampBackgroundColor) {
            this.stampBackgroundColor = stampBackgroundColor;
            return this;
        }

        public Builder stampBackgroundColor(String stampBackgroundColor) {
            this.stampBackgroundColor = Optional.ofNullable(stampBackgroundColor);
            return this;
        }

        /**
         * <p>Hex colour for stamp icons</p>
         */
        @JsonSetter(value = "stamp_color", nulls = Nulls.SKIP)
        public Builder stampColor(Optional<String> stampColor) {
            this.stampColor = stampColor;
            return this;
        }

        public Builder stampColor(String stampColor) {
            this.stampColor = Optional.ofNullable(stampColor);
            return this;
        }

        /**
         * <p>Stamp icon identifier</p>
         */
        @JsonSetter(value = "stamp_icon", nulls = Nulls.SKIP)
        public Builder stampIcon(Optional<String> stampIcon) {
            this.stampIcon = stampIcon;
            return this;
        }

        public Builder stampIcon(String stampIcon) {
            this.stampIcon = Optional.ofNullable(stampIcon);
            return this;
        }

        /**
         * <p>Number of stamps needed (1–21)</p>
         */
        @JsonSetter(value = "stamps_required", nulls = Nulls.SKIP)
        public Builder stampsRequired(Optional<Integer> stampsRequired) {
            this.stampsRequired = stampsRequired;
            return this;
        }

        public Builder stampsRequired(Integer stampsRequired) {
            this.stampsRequired = Optional.ofNullable(stampsRequired);
            return this;
        }

        /**
         * <p>Hex colour for the strip</p>
         */
        @JsonSetter(value = "strip_color", nulls = Nulls.SKIP)
        public Builder stripColor(Optional<String> stripColor) {
            this.stripColor = stripColor;
            return this;
        }

        public Builder stripColor(String stripColor) {
            this.stripColor = Optional.ofNullable(stripColor);
            return this;
        }

        /**
         * <p>Preset strip image identifier</p>
         */
        @JsonSetter(value = "strip_preset", nulls = Nulls.SKIP)
        public Builder stripPreset(Optional<String> stripPreset) {
            this.stripPreset = stripPreset;
            return this;
        }

        public Builder stripPreset(String stripPreset) {
            this.stripPreset = Optional.ofNullable(stripPreset);
            return this;
        }

        /**
         * <p>Strip image type</p>
         */
        @JsonSetter(value = "strip_type", nulls = Nulls.SKIP)
        public Builder stripType(Optional<String> stripType) {
            this.stripType = stripType;
            return this;
        }

        public Builder stripType(String stripType) {
            this.stripType = Optional.ofNullable(stripType);
            return this;
        }

        /**
         * <p>Hex colour for card text</p>
         */
        @JsonSetter(value = "text_color", nulls = Nulls.SKIP)
        public Builder textColor(Optional<String> textColor) {
            this.textColor = textColor;
            return this;
        }

        public Builder textColor(String textColor) {
            this.textColor = Optional.ofNullable(textColor);
            return this;
        }

        public UpdateCardsRequestCard build() {
            return new UpdateCardsRequestCard(
                    cardColor,
                    headerText,
                    initialStamps,
                    name,
                    stampBackgroundColor,
                    stampColor,
                    stampIcon,
                    stampsRequired,
                    stripColor,
                    stripPreset,
                    stripType,
                    textColor,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
