/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customers;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.LealApiException;
import com.getleal.api.core.LealException;
import com.getleal.api.core.LealHttpResponse;
import com.getleal.api.core.MediaTypes;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.core.QueryStringMapper;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.core.RetryInterceptor;
import com.getleal.api.errors.NotFoundError;
import com.getleal.api.errors.TooManyRequestsError;
import com.getleal.api.errors.UnauthorizedError;
import com.getleal.api.errors.UnprocessableEntityError;
import com.getleal.api.resources.customers.requests.CreateCustomersRequest;
import com.getleal.api.resources.customers.requests.GetCustomersRequest;
import com.getleal.api.resources.customers.requests.ListCustomersRequest;
import com.getleal.api.resources.customers.requests.UpdateCustomersRequest;
import com.getleal.api.resources.customers.types.CreateCustomersResponse;
import com.getleal.api.resources.customers.types.GetCustomersResponse;
import com.getleal.api.resources.customers.types.ListCustomersResponse;
import com.getleal.api.resources.customers.types.UpdateCustomersResponse;
import com.getleal.api.types.Error;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawCustomersClient {
    protected final ClientOptions clientOptions;

    public RawCustomersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a paginated list of customers for the store. Use the <code>search</code> parameter to filter
     * by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
     * <code>source</code> AND <code>external_id</code> together to perform an exact lookup by an external reference -
     * the response will contain at most one customer.
     */
    public LealHttpResponse<ListCustomersResponse> list(int accountId) {
        return list(accountId, ListCustomersRequest.builder().build());
    }

    /**
     * Returns a paginated list of customers for the store. Use the <code>search</code> parameter to filter
     * by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
     * <code>source</code> AND <code>external_id</code> together to perform an exact lookup by an external reference -
     * the response will contain at most one customer.
     */
    public LealHttpResponse<ListCustomersResponse> list(int accountId, RequestOptions requestOptions) {
        return list(accountId, ListCustomersRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of customers for the store. Use the <code>search</code> parameter to filter
     * by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
     * <code>source</code> AND <code>external_id</code> together to perform an exact lookup by an external reference -
     * the response will contain at most one customer.
     */
    public LealHttpResponse<ListCustomersResponse> list(int accountId, ListCustomersRequest request) {
        return list(accountId, request, null);
    }

    /**
     * Returns a paginated list of customers for the store. Use the <code>search</code> parameter to filter
     * by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
     * <code>source</code> AND <code>external_id</code> together to perform an exact lookup by an external reference -
     * the response will contain at most one customer.
     */
    public LealHttpResponse<ListCustomersResponse> list(
            int accountId, ListCustomersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers");
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        if (request.getSource().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "source", request.getSource().get(), false);
        }
        if (request.getExternalId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "external_id", request.getExternalId().get(), false);
        }
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getItems().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "items", request.getItems().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListCustomersResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }

    /**
     * Creates a new customer for the store. Requires <code>first_name</code> and at least one of <code>email</code> or <code>phone</code>.
     * Optionally enroll the customer in a loyalty card by passing <code>card_id</code>, and trigger delivery of
     * card links (email/SMS) by passing <code>send_card_links</code>. When a card with initial stamps is assigned,
     * those stamps are automatically applied as a welcome bonus.
     * <p>Pass <code>metadata</code> to attach arbitrary key/value data, and <code>external_references</code> to link the
     * customer to records in other systems (e.g. Square, Shopify). External references are upserted
     * by <code>(source, external_id)</code> so this endpoint is safe to call with the same references twice.</p>
     */
    public LealHttpResponse<CreateCustomersResponse> create(int accountId, CreateCustomersRequest request) {
        return create(accountId, request, null);
    }

    /**
     * Creates a new customer for the store. Requires <code>first_name</code> and at least one of <code>email</code> or <code>phone</code>.
     * Optionally enroll the customer in a loyalty card by passing <code>card_id</code>, and trigger delivery of
     * card links (email/SMS) by passing <code>send_card_links</code>. When a card with initial stamps is assigned,
     * those stamps are automatically applied as a welcome bonus.
     * <p>Pass <code>metadata</code> to attach arbitrary key/value data, and <code>external_references</code> to link the
     * customer to records in other systems (e.g. Square, Shopify). External references are upserted
     * by <code>(source, external_id)</code> so this endpoint is safe to call with the same references twice.</p>
     */
    public LealHttpResponse<CreateCustomersResponse> create(
            int accountId, CreateCustomersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateCustomersResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns detailed information about a single customer, including all of their
     * enrolled loyalty cards with stamp progress and wallet pass URLs (<code>apple_wallet_url</code>
     * and <code>google_wallet_url</code>) for each card. Also includes <code>metadata</code> and
     * <code>external_references</code> so you can sync state with external systems.
     */
    public LealHttpResponse<GetCustomersResponse> get(int accountId, int id) {
        return get(accountId, id, GetCustomersRequest.builder().build());
    }

    /**
     * Returns detailed information about a single customer, including all of their
     * enrolled loyalty cards with stamp progress and wallet pass URLs (<code>apple_wallet_url</code>
     * and <code>google_wallet_url</code>) for each card. Also includes <code>metadata</code> and
     * <code>external_references</code> so you can sync state with external systems.
     */
    public LealHttpResponse<GetCustomersResponse> get(int accountId, int id, RequestOptions requestOptions) {
        return get(accountId, id, GetCustomersRequest.builder().build(), requestOptions);
    }

    /**
     * Returns detailed information about a single customer, including all of their
     * enrolled loyalty cards with stamp progress and wallet pass URLs (<code>apple_wallet_url</code>
     * and <code>google_wallet_url</code>) for each card. Also includes <code>metadata</code> and
     * <code>external_references</code> so you can sync state with external systems.
     */
    public LealHttpResponse<GetCustomersResponse> get(int accountId, int id, GetCustomersRequest request) {
        return get(accountId, id, request, null);
    }

    /**
     * Returns detailed information about a single customer, including all of their
     * enrolled loyalty cards with stamp progress and wallet pass URLs (<code>apple_wallet_url</code>
     * and <code>google_wallet_url</code>) for each card. Also includes <code>metadata</code> and
     * <code>external_references</code> so you can sync state with external systems.
     */
    public LealHttpResponse<GetCustomersResponse> get(
            int accountId, int id, GetCustomersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetCustomersResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates an existing customer's details. To add stamps or redeem rewards, use the
     * customer cards endpoints instead.
     * <p><code>metadata</code> is shallow-merged into the existing metadata. <code>external_references</code> are upserted
     * by <code>(source, external_id)</code> - to remove a reference, omit it from subsequent calls and use
     * a separate <code>DELETE</code> workflow (not yet exposed via API; manage in dashboard for now).</p>
     */
    public LealHttpResponse<UpdateCustomersResponse> update(int accountId, int id, UpdateCustomersRequest request) {
        return update(accountId, id, request, null);
    }

    /**
     * Updates an existing customer's details. To add stamps or redeem rewards, use the
     * customer cards endpoints instead.
     * <p><code>metadata</code> is shallow-merged into the existing metadata. <code>external_references</code> are upserted
     * by <code>(source, external_id)</code> - to remove a reference, omit it from subsequent calls and use
     * a separate <code>DELETE</code> workflow (not yet exposed via API; manage in dashboard for now).</p>
     */
    public LealHttpResponse<UpdateCustomersResponse> update(
            int accountId, int id, UpdateCustomersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateCustomersResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }
}
