/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customercards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RedeemCustomerCardsResponseRedemption.Builder.class)
public final class RedeemCustomerCardsResponseRedemption {
    private final int id;

    private final String redeemedAt;

    private final int rewardId;

    private final String rewardName;

    private final int stampsRemaining;

    private final int stampsSpent;

    private final Map<String, Object> additionalProperties;

    private RedeemCustomerCardsResponseRedemption(
            int id,
            String redeemedAt,
            int rewardId,
            String rewardName,
            int stampsRemaining,
            int stampsSpent,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.redeemedAt = redeemedAt;
        this.rewardId = rewardId;
        this.rewardName = rewardName;
        this.stampsRemaining = stampsRemaining;
        this.stampsSpent = stampsSpent;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Redemption ID
     */
    @JsonProperty("id")
    public int getId() {
        return id;
    }

    /**
     * @return ISO 8601 timestamp of the redemption
     */
    @JsonProperty("redeemed_at")
    public String getRedeemedAt() {
        return redeemedAt;
    }

    /**
     * @return Reward that was redeemed
     */
    @JsonProperty("reward_id")
    public int getRewardId() {
        return rewardId;
    }

    /**
     * @return Display name of the reward
     */
    @JsonProperty("reward_name")
    public String getRewardName() {
        return rewardName;
    }

    /**
     * @return Stamps left on the card afterwards
     */
    @JsonProperty("stamps_remaining")
    public int getStampsRemaining() {
        return stampsRemaining;
    }

    /**
     * @return Stamps deducted from the card
     */
    @JsonProperty("stamps_spent")
    public int getStampsSpent() {
        return stampsSpent;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RedeemCustomerCardsResponseRedemption
                && equalTo((RedeemCustomerCardsResponseRedemption) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RedeemCustomerCardsResponseRedemption other) {
        return id == other.id
                && redeemedAt.equals(other.redeemedAt)
                && rewardId == other.rewardId
                && rewardName.equals(other.rewardName)
                && stampsRemaining == other.stampsRemaining
                && stampsSpent == other.stampsSpent;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id, this.redeemedAt, this.rewardId, this.rewardName, this.stampsRemaining, this.stampsSpent);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Redemption ID</p>
         */
        RedeemedAtStage id(int id);

        Builder from(RedeemCustomerCardsResponseRedemption other);
    }

    public interface RedeemedAtStage {
        /**
         * <p>ISO 8601 timestamp of the redemption</p>
         */
        RewardIdStage redeemedAt(@NotNull String redeemedAt);
    }

    public interface RewardIdStage {
        /**
         * <p>Reward that was redeemed</p>
         */
        RewardNameStage rewardId(int rewardId);
    }

    public interface RewardNameStage {
        /**
         * <p>Display name of the reward</p>
         */
        StampsRemainingStage rewardName(@NotNull String rewardName);
    }

    public interface StampsRemainingStage {
        /**
         * <p>Stamps left on the card afterwards</p>
         */
        StampsSpentStage stampsRemaining(int stampsRemaining);
    }

    public interface StampsSpentStage {
        /**
         * <p>Stamps deducted from the card</p>
         */
        _FinalStage stampsSpent(int stampsSpent);
    }

    public interface _FinalStage {
        RedeemCustomerCardsResponseRedemption build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    RedeemedAtStage,
                    RewardIdStage,
                    RewardNameStage,
                    StampsRemainingStage,
                    StampsSpentStage,
                    _FinalStage {
        private int id;

        private String redeemedAt;

        private int rewardId;

        private String rewardName;

        private int stampsRemaining;

        private int stampsSpent;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RedeemCustomerCardsResponseRedemption other) {
            id(other.getId());
            redeemedAt(other.getRedeemedAt());
            rewardId(other.getRewardId());
            rewardName(other.getRewardName());
            stampsRemaining(other.getStampsRemaining());
            stampsSpent(other.getStampsSpent());
            return this;
        }

        /**
         * <p>Redemption ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public RedeemedAtStage id(int id) {
            this.id = id;
            return this;
        }

        /**
         * <p>ISO 8601 timestamp of the redemption</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("redeemed_at")
        public RewardIdStage redeemedAt(@NotNull String redeemedAt) {
            this.redeemedAt = Objects.requireNonNull(redeemedAt, "redeemedAt must not be null");
            return this;
        }

        /**
         * <p>Reward that was redeemed</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reward_id")
        public RewardNameStage rewardId(int rewardId) {
            this.rewardId = rewardId;
            return this;
        }

        /**
         * <p>Display name of the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reward_name")
        public StampsRemainingStage rewardName(@NotNull String rewardName) {
            this.rewardName = Objects.requireNonNull(rewardName, "rewardName must not be null");
            return this;
        }

        /**
         * <p>Stamps left on the card afterwards</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stamps_remaining")
        public StampsSpentStage stampsRemaining(int stampsRemaining) {
            this.stampsRemaining = stampsRemaining;
            return this;
        }

        /**
         * <p>Stamps deducted from the card</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stamps_spent")
        public _FinalStage stampsSpent(int stampsSpent) {
            this.stampsSpent = stampsSpent;
            return this;
        }

        @java.lang.Override
        public RedeemCustomerCardsResponseRedemption build() {
            return new RedeemCustomerCardsResponseRedemption(
                    id, redeemedAt, rewardId, rewardName, stampsRemaining, stampsSpent, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
