/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.cards;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.cards.requests.CreateCardsRequest;
import com.getleal.api.resources.cards.requests.GetCardsRequest;
import com.getleal.api.resources.cards.requests.ListCardsRequest;
import com.getleal.api.resources.cards.requests.UpdateCardsRequest;
import com.getleal.api.resources.cards.types.CreateCardsResponse;
import com.getleal.api.resources.cards.types.GetCardsResponse;
import com.getleal.api.resources.cards.types.ListCardsResponseItem;
import com.getleal.api.resources.cards.types.UpdateCardsResponse;
import java.util.List;

public class CardsClient {
    protected final ClientOptions clientOptions;

    private final RawCardsClient rawClient;

    public CardsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawCardsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawCardsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns loyalty card templates for the specified store. By default, only
     * active (unarchived) cards are returned. Use the <code>scope</code> parameter to include
     * archived cards.
     */
    public List<ListCardsResponseItem> list(int accountId) {
        return this.rawClient.list(accountId).body();
    }

    /**
     * Returns loyalty card templates for the specified store. By default, only
     * active (unarchived) cards are returned. Use the <code>scope</code> parameter to include
     * archived cards.
     */
    public List<ListCardsResponseItem> list(int accountId, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, requestOptions).body();
    }

    /**
     * Returns loyalty card templates for the specified store. By default, only
     * active (unarchived) cards are returned. Use the <code>scope</code> parameter to include
     * archived cards.
     */
    public List<ListCardsResponseItem> list(int accountId, ListCardsRequest request) {
        return this.rawClient.list(accountId, request).body();
    }

    /**
     * Returns loyalty card templates for the specified store. By default, only
     * active (unarchived) cards are returned. Use the <code>scope</code> parameter to include
     * archived cards.
     */
    public List<ListCardsResponseItem> list(int accountId, ListCardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, request, requestOptions).body();
    }

    /**
     * Creates a new loyalty stamp card template for the store. The card defines the
     * visual design (colours, icon, strip) and program rules (stamps required,
     * initial stamps).
     */
    public CreateCardsResponse create(int accountId, CreateCardsRequest request) {
        return this.rawClient.create(accountId, request).body();
    }

    /**
     * Creates a new loyalty stamp card template for the store. The card defines the
     * visual design (colours, icon, strip) and program rules (stamps required,
     * initial stamps).
     */
    public CreateCardsResponse create(int accountId, CreateCardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(accountId, request, requestOptions).body();
    }

    /**
     * Returns a single loyalty card template by ID, including reward and customer card counts.
     */
    public GetCardsResponse get(int accountId, int id) {
        return this.rawClient.get(accountId, id).body();
    }

    /**
     * Returns a single loyalty card template by ID, including reward and customer card counts.
     */
    public GetCardsResponse get(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, requestOptions).body();
    }

    /**
     * Returns a single loyalty card template by ID, including reward and customer card counts.
     */
    public GetCardsResponse get(int accountId, int id, GetCardsRequest request) {
        return this.rawClient.get(accountId, id, request).body();
    }

    /**
     * Returns a single loyalty card template by ID, including reward and customer card counts.
     */
    public GetCardsResponse get(int accountId, int id, GetCardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, request, requestOptions).body();
    }

    /**
     * Updates an existing loyalty card template. Only the provided attributes are changed.
     */
    public UpdateCardsResponse update(int accountId, int id, UpdateCardsRequest request) {
        return this.rawClient.update(accountId, id, request).body();
    }

    /**
     * Updates an existing loyalty card template. Only the provided attributes are changed.
     */
    public UpdateCardsResponse update(
            int accountId, int id, UpdateCardsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(accountId, id, request, requestOptions).body();
    }
}
