/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.locations;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.locations.requests.CreateLocationsRequest;
import com.getleal.api.resources.locations.requests.DeleteLocationsRequest;
import com.getleal.api.resources.locations.requests.GetLocationsRequest;
import com.getleal.api.resources.locations.requests.ListLocationsRequest;
import com.getleal.api.resources.locations.requests.UpdateLocationsRequest;
import com.getleal.api.resources.locations.types.CreateLocationsResponse;
import com.getleal.api.resources.locations.types.GetLocationsResponse;
import com.getleal.api.resources.locations.types.ListLocationsResponseItem;
import com.getleal.api.resources.locations.types.UpdateLocationsResponse;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncLocationsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawLocationsClient rawClient;

    public AsyncLocationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawLocationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawLocationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns every physical location belonging to the specified store.
     */
    public CompletableFuture<List<ListLocationsResponseItem>> list(int accountId) {
        return this.rawClient.list(accountId).thenApply(response -> response.body());
    }

    /**
     * Returns every physical location belonging to the specified store.
     */
    public CompletableFuture<List<ListLocationsResponseItem>> list(int accountId, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns every physical location belonging to the specified store.
     */
    public CompletableFuture<List<ListLocationsResponseItem>> list(int accountId, ListLocationsRequest request) {
        return this.rawClient.list(accountId, request).thenApply(response -> response.body());
    }

    /**
     * Returns every physical location belonging to the specified store.
     */
    public CompletableFuture<List<ListLocationsResponseItem>> list(
            int accountId, ListLocationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Creates a new physical location for the store. The provided address is
     * automatically geocoded to latitude and longitude coordinates in the background.
     */
    public CompletableFuture<CreateLocationsResponse> create(int accountId, CreateLocationsRequest request) {
        return this.rawClient.create(accountId, request).thenApply(response -> response.body());
    }

    /**
     * Creates a new physical location for the store. The provided address is
     * automatically geocoded to latitude and longitude coordinates in the background.
     */
    public CompletableFuture<CreateLocationsResponse> create(
            int accountId, CreateLocationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(accountId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single location by ID.
     */
    public CompletableFuture<GetLocationsResponse> get(int accountId, int id) {
        return this.rawClient.get(accountId, id).thenApply(response -> response.body());
    }

    /**
     * Returns a single location by ID.
     */
    public CompletableFuture<GetLocationsResponse> get(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single location by ID.
     */
    public CompletableFuture<GetLocationsResponse> get(int accountId, int id, GetLocationsRequest request) {
        return this.rawClient.get(accountId, id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a single location by ID.
     */
    public CompletableFuture<GetLocationsResponse> get(
            int accountId, int id, GetLocationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a location. This action cannot be undone.
     */
    public CompletableFuture<Void> delete(int accountId, int id) {
        return this.rawClient.delete(accountId, id).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a location. This action cannot be undone.
     */
    public CompletableFuture<Void> delete(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.delete(accountId, id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a location. This action cannot be undone.
     */
    public CompletableFuture<Void> delete(int accountId, int id, DeleteLocationsRequest request) {
        return this.rawClient.delete(accountId, id, request).thenApply(response -> response.body());
    }

    /**
     * Permanently deletes a location. This action cannot be undone.
     */
    public CompletableFuture<Void> delete(
            int accountId, int id, DeleteLocationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(accountId, id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates an existing location. If the address is changed, it will be re-geocoded automatically.
     */
    public CompletableFuture<UpdateLocationsResponse> update(int accountId, int id, UpdateLocationsRequest request) {
        return this.rawClient.update(accountId, id, request).thenApply(response -> response.body());
    }

    /**
     * Updates an existing location. If the address is changed, it will be re-geocoded automatically.
     */
    public CompletableFuture<UpdateLocationsResponse> update(
            int accountId, int id, UpdateLocationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(accountId, id, request, requestOptions).thenApply(response -> response.body());
    }
}
