/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.posters;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.posters.requests.CreatePostersRequest;
import com.getleal.api.resources.posters.requests.DeletePostersRequest;
import com.getleal.api.resources.posters.requests.GetPostersRequest;
import com.getleal.api.resources.posters.requests.ListPostersRequest;
import com.getleal.api.resources.posters.requests.UpdatePostersRequest;
import com.getleal.api.resources.posters.types.CreatePostersResponse;
import com.getleal.api.resources.posters.types.GetPostersResponse;
import com.getleal.api.resources.posters.types.ListPostersResponseItem;
import com.getleal.api.resources.posters.types.UpdatePostersResponse;
import java.util.List;

public class PostersClient {
    protected final ClientOptions clientOptions;

    private final RawPostersClient rawClient;

    public PostersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPostersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPostersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all posters for the store. Optionally filter by card or active status.
     */
    public List<ListPostersResponseItem> list(int accountId) {
        return this.rawClient.list(accountId).body();
    }

    /**
     * Returns all posters for the store. Optionally filter by card or active status.
     */
    public List<ListPostersResponseItem> list(int accountId, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, requestOptions).body();
    }

    /**
     * Returns all posters for the store. Optionally filter by card or active status.
     */
    public List<ListPostersResponseItem> list(int accountId, ListPostersRequest request) {
        return this.rawClient.list(accountId, request).body();
    }

    /**
     * Returns all posters for the store. Optionally filter by card or active status.
     */
    public List<ListPostersResponseItem> list(
            int accountId, ListPostersRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(accountId, request, requestOptions).body();
    }

    /**
     * Creates a new printable QR code poster for customer signup. The poster will automatically
     * generate a unique public signup URL and QR code. The <code>card_id</code> is required on create to
     * associate the poster with a loyalty card.
     */
    public CreatePostersResponse create(int accountId, CreatePostersRequest request) {
        return this.rawClient.create(accountId, request).body();
    }

    /**
     * Creates a new printable QR code poster for customer signup. The poster will automatically
     * generate a unique public signup URL and QR code. The <code>card_id</code> is required on create to
     * associate the poster with a loyalty card.
     */
    public CreatePostersResponse create(int accountId, CreatePostersRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(accountId, request, requestOptions).body();
    }

    /**
     * Returns a single poster by ID, including generated signup and display URLs.
     */
    public GetPostersResponse get(int accountId, int id) {
        return this.rawClient.get(accountId, id).body();
    }

    /**
     * Returns a single poster by ID, including generated signup and display URLs.
     */
    public GetPostersResponse get(int accountId, int id, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, requestOptions).body();
    }

    /**
     * Returns a single poster by ID, including generated signup and display URLs.
     */
    public GetPostersResponse get(int accountId, int id, GetPostersRequest request) {
        return this.rawClient.get(accountId, id, request).body();
    }

    /**
     * Returns a single poster by ID, including generated signup and display URLs.
     */
    public GetPostersResponse get(int accountId, int id, GetPostersRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(accountId, id, request, requestOptions).body();
    }

    /**
     * Permanently deletes a poster. The public signup URL will stop working.
     */
    public void delete(int accountId, int id) {
        this.rawClient.delete(accountId, id).body();
    }

    /**
     * Permanently deletes a poster. The public signup URL will stop working.
     */
    public void delete(int accountId, int id, RequestOptions requestOptions) {
        this.rawClient.delete(accountId, id, requestOptions).body();
    }

    /**
     * Permanently deletes a poster. The public signup URL will stop working.
     */
    public void delete(int accountId, int id, DeletePostersRequest request) {
        this.rawClient.delete(accountId, id, request).body();
    }

    /**
     * Permanently deletes a poster. The public signup URL will stop working.
     */
    public void delete(int accountId, int id, DeletePostersRequest request, RequestOptions requestOptions) {
        this.rawClient.delete(accountId, id, request, requestOptions).body();
    }

    /**
     * Updates an existing poster. The <code>card_id</code> cannot be changed after creation.
     */
    public UpdatePostersResponse update(int accountId, int id, UpdatePostersRequest request) {
        return this.rawClient.update(accountId, id, request).body();
    }

    /**
     * Updates an existing poster. The <code>card_id</code> cannot be changed after creation.
     */
    public UpdatePostersResponse update(
            int accountId, int id, UpdatePostersRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(accountId, id, request, requestOptions).body();
    }
}
