/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.stores.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateStoresRequestAccount.Builder.class)
public final class UpdateStoresRequestAccount {
    private final Optional<String> name;

    private final Optional<String> storeName;

    private final Map<String, Object> additionalProperties;

    private UpdateStoresRequestAccount(
            Optional<String> name, Optional<String> storeName, Map<String, Object> additionalProperties) {
        this.name = name;
        this.storeName = storeName;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Internal account name
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Public-facing store name shown to customers
     */
    @JsonProperty("store_name")
    public Optional<String> getStoreName() {
        return storeName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateStoresRequestAccount && equalTo((UpdateStoresRequestAccount) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateStoresRequestAccount other) {
        return name.equals(other.name) && storeName.equals(other.storeName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.storeName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> storeName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateStoresRequestAccount other) {
            name(other.getName());
            storeName(other.getStoreName());
            return this;
        }

        /**
         * <p>Internal account name</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Public-facing store name shown to customers</p>
         */
        @JsonSetter(value = "store_name", nulls = Nulls.SKIP)
        public Builder storeName(Optional<String> storeName) {
            this.storeName = storeName;
            return this;
        }

        public Builder storeName(String storeName) {
            this.storeName = Optional.ofNullable(storeName);
            return this;
        }

        public UpdateStoresRequestAccount build() {
            return new UpdateStoresRequestAccount(name, storeName, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
