/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customercards;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.LealApiException;
import com.getleal.api.core.LealException;
import com.getleal.api.core.LealHttpResponse;
import com.getleal.api.core.MediaTypes;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.core.RetryInterceptor;
import com.getleal.api.errors.GoneError;
import com.getleal.api.errors.NotFoundError;
import com.getleal.api.errors.TooManyRequestsError;
import com.getleal.api.errors.UnauthorizedError;
import com.getleal.api.errors.UnprocessableEntityError;
import com.getleal.api.resources.customercards.requests.GetCustomerCardsRequest;
import com.getleal.api.resources.customercards.requests.ListCustomerCardsRequest;
import com.getleal.api.resources.customercards.requests.RedeemCustomerCardsRequest;
import com.getleal.api.resources.customercards.requests.StampCustomerCardsRequest;
import com.getleal.api.resources.customercards.types.GetCustomerCardsResponse;
import com.getleal.api.resources.customercards.types.ListCustomerCardsResponseItem;
import com.getleal.api.resources.customercards.types.RedeemCustomerCardsResponse;
import com.getleal.api.resources.customercards.types.StampCustomerCardsResponse;
import com.getleal.api.types.Error;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawCustomerCardsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawCustomerCardsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns all loyalty cards enrolled for a specific customer, including stamp progress,
     * status, wallet pass installation state, and wallet pass URLs (<code>apple_wallet_url</code> and
     * <code>google_wallet_url</code>) that you can use to let customers add their loyalty card to
     * Apple Wallet or Google Wallet from your own app or website.
     */
    public CompletableFuture<LealHttpResponse<List<ListCustomerCardsResponseItem>>> list(
            int accountId, int customerId) {
        return list(accountId, customerId, ListCustomerCardsRequest.builder().build());
    }

    /**
     * Returns all loyalty cards enrolled for a specific customer, including stamp progress,
     * status, wallet pass installation state, and wallet pass URLs (<code>apple_wallet_url</code> and
     * <code>google_wallet_url</code>) that you can use to let customers add their loyalty card to
     * Apple Wallet or Google Wallet from your own app or website.
     */
    public CompletableFuture<LealHttpResponse<List<ListCustomerCardsResponseItem>>> list(
            int accountId, int customerId, RequestOptions requestOptions) {
        return list(accountId, customerId, ListCustomerCardsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns all loyalty cards enrolled for a specific customer, including stamp progress,
     * status, wallet pass installation state, and wallet pass URLs (<code>apple_wallet_url</code> and
     * <code>google_wallet_url</code>) that you can use to let customers add their loyalty card to
     * Apple Wallet or Google Wallet from your own app or website.
     */
    public CompletableFuture<LealHttpResponse<List<ListCustomerCardsResponseItem>>> list(
            int accountId, int customerId, ListCustomerCardsRequest request) {
        return list(accountId, customerId, request, null);
    }

    /**
     * Returns all loyalty cards enrolled for a specific customer, including stamp progress,
     * status, wallet pass installation state, and wallet pass URLs (<code>apple_wallet_url</code> and
     * <code>google_wallet_url</code>) that you can use to let customers add their loyalty card to
     * Apple Wallet or Google Wallet from your own app or website.
     */
    public CompletableFuture<LealHttpResponse<List<ListCustomerCardsResponseItem>>> list(
            int accountId, int customerId, ListCustomerCardsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers")
                .addPathSegment(Integer.toString(customerId))
                .addPathSegments("customer_cards");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<LealHttpResponse<List<ListCustomerCardsResponseItem>>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new LealHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString,
                                        new TypeReference<List<ListCustomerCardsResponseItem>>() {}),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 410:
                                future.completeExceptionally(new GoneError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new LealApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new LealException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new LealException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new LealException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns detailed information about a specific customer card, including stamp progress,
     * a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
     * (<code>apple_wallet_url</code> and <code>google_wallet_url</code>) for adding the card to Apple Wallet or
     * Google Wallet.
     */
    public CompletableFuture<LealHttpResponse<GetCustomerCardsResponse>> get(int accountId, int customerId, int id) {
        return get(accountId, customerId, id, GetCustomerCardsRequest.builder().build());
    }

    /**
     * Returns detailed information about a specific customer card, including stamp progress,
     * a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
     * (<code>apple_wallet_url</code> and <code>google_wallet_url</code>) for adding the card to Apple Wallet or
     * Google Wallet.
     */
    public CompletableFuture<LealHttpResponse<GetCustomerCardsResponse>> get(
            int accountId, int customerId, int id, RequestOptions requestOptions) {
        return get(accountId, customerId, id, GetCustomerCardsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns detailed information about a specific customer card, including stamp progress,
     * a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
     * (<code>apple_wallet_url</code> and <code>google_wallet_url</code>) for adding the card to Apple Wallet or
     * Google Wallet.
     */
    public CompletableFuture<LealHttpResponse<GetCustomerCardsResponse>> get(
            int accountId, int customerId, int id, GetCustomerCardsRequest request) {
        return get(accountId, customerId, id, request, null);
    }

    /**
     * Returns detailed information about a specific customer card, including stamp progress,
     * a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
     * (<code>apple_wallet_url</code> and <code>google_wallet_url</code>) for adding the card to Apple Wallet or
     * Google Wallet.
     */
    public CompletableFuture<LealHttpResponse<GetCustomerCardsResponse>> get(
            int accountId, int customerId, int id, GetCustomerCardsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers")
                .addPathSegment(Integer.toString(customerId))
                .addPathSegments("customer_cards")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<LealHttpResponse<GetCustomerCardsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new LealHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetCustomerCardsResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 410:
                                future.completeExceptionally(new GoneError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new LealApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new LealException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new LealException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new LealException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Redeems a reward for a customer, deducting the required stamps from their card.
     * The customer must have enough stamps on this card to cover the reward's cost.
     * Triggers wallet pass updates and push notifications.
     */
    public CompletableFuture<LealHttpResponse<RedeemCustomerCardsResponse>> redeem(
            int accountId, int customerId, int id, RedeemCustomerCardsRequest request) {
        return redeem(accountId, customerId, id, request, null);
    }

    /**
     * Redeems a reward for a customer, deducting the required stamps from their card.
     * The customer must have enough stamps on this card to cover the reward's cost.
     * Triggers wallet pass updates and push notifications.
     */
    public CompletableFuture<LealHttpResponse<RedeemCustomerCardsResponse>> redeem(
            int accountId, int customerId, int id, RedeemCustomerCardsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers")
                .addPathSegment(Integer.toString(customerId))
                .addPathSegments("customer_cards")
                .addPathSegment(Integer.toString(id))
                .addPathSegments("redeem");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<LealHttpResponse<RedeemCustomerCardsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new LealHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, RedeemCustomerCardsResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 410:
                                future.completeExceptionally(new GoneError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new LealApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new LealException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new LealException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new LealException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Adds stamps to a customer's loyalty card. Triggers ledger entries, wallet pass updates,
     * and push notifications. Pass <code>skip_notifications</code> to stamp silently.
     */
    public CompletableFuture<LealHttpResponse<StampCustomerCardsResponse>> stamp(
            int accountId, int customerId, int id, StampCustomerCardsRequest request) {
        return stamp(accountId, customerId, id, request, null);
    }

    /**
     * Adds stamps to a customer's loyalty card. Triggers ledger entries, wallet pass updates,
     * and push notifications. Pass <code>skip_notifications</code> to stamp silently.
     */
    public CompletableFuture<LealHttpResponse<StampCustomerCardsResponse>> stamp(
            int accountId, int customerId, int id, StampCustomerCardsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/accounts")
                .addPathSegment(Integer.toString(accountId))
                .addPathSegments("customers")
                .addPathSegment(Integer.toString(customerId))
                .addPathSegments("customer_cards")
                .addPathSegment(Integer.toString(id))
                .addPathSegments("stamp");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<LealHttpResponse<StampCustomerCardsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new LealHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, StampCustomerCardsResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 410:
                                future.completeExceptionally(new GoneError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new LealApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new LealException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new LealException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new LealException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
