/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.locations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateLocationsRequestLocation.Builder.class)
public final class UpdateLocationsRequestLocation {
    private final Optional<String> address;

    private final Optional<String> name;

    private final Map<String, Object> additionalProperties;

    private UpdateLocationsRequestLocation(
            Optional<String> address, Optional<String> name, Map<String, Object> additionalProperties) {
        this.address = address;
        this.name = name;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Full street address – automatically geocoded to lat/lng
     */
    @JsonProperty("address")
    public Optional<String> getAddress() {
        return address;
    }

    /**
     * @return Location name
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateLocationsRequestLocation && equalTo((UpdateLocationsRequestLocation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateLocationsRequestLocation other) {
        return address.equals(other.address) && name.equals(other.name);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.address, this.name);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> address = Optional.empty();

        private Optional<String> name = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateLocationsRequestLocation other) {
            address(other.getAddress());
            name(other.getName());
            return this;
        }

        /**
         * <p>Full street address – automatically geocoded to lat/lng</p>
         */
        @JsonSetter(value = "address", nulls = Nulls.SKIP)
        public Builder address(Optional<String> address) {
            this.address = address;
            return this;
        }

        public Builder address(String address) {
            this.address = Optional.ofNullable(address);
            return this;
        }

        /**
         * <p>Location name</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        public UpdateLocationsRequestLocation build() {
            return new UpdateLocationsRequestLocation(address, name, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
