/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.rewards.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.resources.rewards.types.CreateRewardsRequestReward;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateRewardsRequest.Builder.class)
public final class CreateRewardsRequest {
    private final CreateRewardsRequestReward reward;

    private final Map<String, Object> additionalProperties;

    private CreateRewardsRequest(CreateRewardsRequestReward reward, Map<String, Object> additionalProperties) {
        this.reward = reward;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("reward")
    public CreateRewardsRequestReward getReward() {
        return reward;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateRewardsRequest && equalTo((CreateRewardsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateRewardsRequest other) {
        return reward.equals(other.reward);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.reward);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RewardStage builder() {
        return new Builder();
    }

    public interface RewardStage {
        _FinalStage reward(@NotNull CreateRewardsRequestReward reward);

        Builder from(CreateRewardsRequest other);
    }

    public interface _FinalStage {
        CreateRewardsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RewardStage, _FinalStage {
        private CreateRewardsRequestReward reward;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateRewardsRequest other) {
            reward(other.getReward());
            return this;
        }

        @java.lang.Override
        @JsonSetter("reward")
        public _FinalStage reward(@NotNull CreateRewardsRequestReward reward) {
            this.reward = Objects.requireNonNull(reward, "reward must not be null");
            return this;
        }

        @java.lang.Override
        public CreateRewardsRequest build() {
            return new CreateRewardsRequest(reward, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
