/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.cards.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListCardsRequest.Builder.class)
public final class ListCardsRequest {
    private final Optional<String> scope;

    private final Map<String, Object> additionalProperties;

    private ListCardsRequest(Optional<String> scope, Map<String, Object> additionalProperties) {
        this.scope = scope;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter cards by archive status. Default: active only.
     */
    @JsonProperty("scope")
    public Optional<String> getScope() {
        return scope;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListCardsRequest && equalTo((ListCardsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListCardsRequest other) {
        return scope.equals(other.scope);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.scope);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> scope = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListCardsRequest other) {
            scope(other.getScope());
            return this;
        }

        /**
         * <p>Filter cards by archive status. Default: active only.</p>
         */
        @JsonSetter(value = "scope", nulls = Nulls.SKIP)
        public Builder scope(Optional<String> scope) {
            this.scope = scope;
            return this;
        }

        public Builder scope(String scope) {
            this.scope = Optional.ofNullable(scope);
            return this;
        }

        public ListCardsRequest build() {
            return new ListCardsRequest(scope, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
