/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.cards.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.resources.cards.types.UpdateCardsRequestCard;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateCardsRequest.Builder.class)
public final class UpdateCardsRequest {
    private final UpdateCardsRequestCard card;

    private final Map<String, Object> additionalProperties;

    private UpdateCardsRequest(UpdateCardsRequestCard card, Map<String, Object> additionalProperties) {
        this.card = card;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("card")
    public UpdateCardsRequestCard getCard() {
        return card;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateCardsRequest && equalTo((UpdateCardsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateCardsRequest other) {
        return card.equals(other.card);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.card);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CardStage builder() {
        return new Builder();
    }

    public interface CardStage {
        _FinalStage card(@NotNull UpdateCardsRequestCard card);

        Builder from(UpdateCardsRequest other);
    }

    public interface _FinalStage {
        UpdateCardsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CardStage, _FinalStage {
        private UpdateCardsRequestCard card;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateCardsRequest other) {
            card(other.getCard());
            return this;
        }

        @java.lang.Override
        @JsonSetter("card")
        public _FinalStage card(@NotNull UpdateCardsRequestCard card) {
            this.card = Objects.requireNonNull(card, "card must not be null");
            return this;
        }

        @java.lang.Override
        public UpdateCardsRequest build() {
            return new UpdateCardsRequest(card, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
