/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.status;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.status.types.CheckStatusResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncStatusClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawStatusClient rawClient;

    public AsyncStatusClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawStatusClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawStatusClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns the status of the API. No authentication required.
     * <p>Every response from this API, including this one, carries <code>RateLimit-Limit</code>,
     * <code>RateLimit-Remaining</code>, <code>RateLimit-Reset</code> and <code>RateLimit-Policy</code>. Exceeding
     * the limit returns 429 with <code>Retry-After</code> in seconds.</p>
     */
    public CompletableFuture<CheckStatusResponse> check() {
        return this.rawClient.check().thenApply(response -> response.body());
    }

    /**
     * Returns the status of the API. No authentication required.
     * <p>Every response from this API, including this one, carries <code>RateLimit-Limit</code>,
     * <code>RateLimit-Remaining</code>, <code>RateLimit-Reset</code> and <code>RateLimit-Policy</code>. Exceeding
     * the limit returns 429 with <code>Retry-After</code> in seconds.</p>
     */
    public CompletableFuture<CheckStatusResponse> check(RequestOptions requestOptions) {
        return this.rawClient.check(requestOptions).thenApply(response -> response.body());
    }
}
