/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.status;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.LealApiException;
import com.getleal.api.core.LealException;
import com.getleal.api.core.LealHttpResponse;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.core.RetryInterceptor;
import com.getleal.api.errors.GoneError;
import com.getleal.api.errors.TooManyRequestsError;
import com.getleal.api.resources.status.types.CheckStatusResponse;
import com.getleal.api.types.Error;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawStatusClient {
    protected final ClientOptions clientOptions;

    public RawStatusClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns the status of the API. No authentication required.
     * <p>Every response from this API, including this one, carries <code>RateLimit-Limit</code>,
     * <code>RateLimit-Remaining</code>, <code>RateLimit-Reset</code> and <code>RateLimit-Policy</code>. Exceeding
     * the limit returns 429 with <code>Retry-After</code> in seconds.</p>
     */
    public LealHttpResponse<CheckStatusResponse> check() {
        return check(null);
    }

    /**
     * Returns the status of the API. No authentication required.
     * <p>Every response from this API, including this one, carries <code>RateLimit-Limit</code>,
     * <code>RateLimit-Remaining</code>, <code>RateLimit-Reset</code> and <code>RateLimit-Policy</code>. Exceeding
     * the limit returns 429 with <code>Retry-After</code> in seconds.</p>
     */
    public LealHttpResponse<CheckStatusResponse> check(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/status");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LealHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CheckStatusResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 410:
                        throw new GoneError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LealApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new LealException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new LealException("Network error executing HTTP request", e);
        }
    }
}
