/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.status;

import com.getleal.api.core.ClientOptions;
import com.getleal.api.core.RequestOptions;
import com.getleal.api.resources.status.types.CheckStatusResponse;

public class StatusClient {
    protected final ClientOptions clientOptions;

    private final RawStatusClient rawClient;

    public StatusClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawStatusClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawStatusClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns the status of the API. No authentication required.
     * <p>Every response from this API, including this one, carries <code>RateLimit-Limit</code>,
     * <code>RateLimit-Remaining</code>, <code>RateLimit-Reset</code> and <code>RateLimit-Policy</code>. Exceeding
     * the limit returns 429 with <code>Retry-After</code> in seconds.</p>
     */
    public CheckStatusResponse check() {
        return this.rawClient.check().body();
    }

    /**
     * Returns the status of the API. No authentication required.
     * <p>Every response from this API, including this one, carries <code>RateLimit-Limit</code>,
     * <code>RateLimit-Remaining</code>, <code>RateLimit-Reset</code> and <code>RateLimit-Policy</code>. Exceeding
     * the limit returns 429 with <code>Retry-After</code> in seconds.</p>
     */
    public CheckStatusResponse check(RequestOptions requestOptions) {
        return this.rawClient.check(requestOptions).body();
    }
}
