/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.posters.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.resources.posters.types.CreatePostersRequestPoster;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreatePostersRequest.Builder.class)
public final class CreatePostersRequest {
    private final CreatePostersRequestPoster poster;

    private final Map<String, Object> additionalProperties;

    private CreatePostersRequest(CreatePostersRequestPoster poster, Map<String, Object> additionalProperties) {
        this.poster = poster;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("poster")
    public CreatePostersRequestPoster getPoster() {
        return poster;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreatePostersRequest && equalTo((CreatePostersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreatePostersRequest other) {
        return poster.equals(other.poster);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.poster);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PosterStage builder() {
        return new Builder();
    }

    public interface PosterStage {
        _FinalStage poster(@NotNull CreatePostersRequestPoster poster);

        Builder from(CreatePostersRequest other);
    }

    public interface _FinalStage {
        CreatePostersRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PosterStage, _FinalStage {
        private CreatePostersRequestPoster poster;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreatePostersRequest other) {
            poster(other.getPoster());
            return this;
        }

        @java.lang.Override
        @JsonSetter("poster")
        public _FinalStage poster(@NotNull CreatePostersRequestPoster poster) {
            this.poster = Objects.requireNonNull(poster, "poster must not be null");
            return this;
        }

        @java.lang.Override
        public CreatePostersRequest build() {
            return new CreatePostersRequest(poster, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
