/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.resources.customers.types.CreateCustomersRequestCustomer;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateCustomersRequest.Builder.class)
public final class CreateCustomersRequest {
    private final Optional<Integer> cardId;

    private final CreateCustomersRequestCustomer customer;

    private final Optional<Boolean> sendCardLinks;

    private final Map<String, Object> additionalProperties;

    private CreateCustomersRequest(
            Optional<Integer> cardId,
            CreateCustomersRequestCustomer customer,
            Optional<Boolean> sendCardLinks,
            Map<String, Object> additionalProperties) {
        this.cardId = cardId;
        this.customer = customer;
        this.sendCardLinks = sendCardLinks;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Loyalty card ID to auto-enroll the customer in
     */
    @JsonProperty("card_id")
    public Optional<Integer> getCardId() {
        return cardId;
    }

    @JsonProperty("customer")
    public CreateCustomersRequestCustomer getCustomer() {
        return customer;
    }

    /**
     * @return When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes <code>apple_wallet_url</code> and <code>google_wallet_url</code> in each customer card object so you can deliver them yourself.
     */
    @JsonProperty("send_card_links")
    public Optional<Boolean> getSendCardLinks() {
        return sendCardLinks;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateCustomersRequest && equalTo((CreateCustomersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateCustomersRequest other) {
        return cardId.equals(other.cardId)
                && customer.equals(other.customer)
                && sendCardLinks.equals(other.sendCardLinks);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.cardId, this.customer, this.sendCardLinks);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CustomerStage builder() {
        return new Builder();
    }

    public interface CustomerStage {
        _FinalStage customer(@NotNull CreateCustomersRequestCustomer customer);

        Builder from(CreateCustomersRequest other);
    }

    public interface _FinalStage {
        CreateCustomersRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Loyalty card ID to auto-enroll the customer in</p>
         */
        _FinalStage cardId(Optional<Integer> cardId);

        _FinalStage cardId(Integer cardId);

        /**
         * <p>When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes <code>apple_wallet_url</code> and <code>google_wallet_url</code> in each customer card object so you can deliver them yourself.</p>
         */
        _FinalStage sendCardLinks(Optional<Boolean> sendCardLinks);

        _FinalStage sendCardLinks(Boolean sendCardLinks);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CustomerStage, _FinalStage {
        private CreateCustomersRequestCustomer customer;

        private Optional<Boolean> sendCardLinks = Optional.empty();

        private Optional<Integer> cardId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateCustomersRequest other) {
            cardId(other.getCardId());
            customer(other.getCustomer());
            sendCardLinks(other.getSendCardLinks());
            return this;
        }

        @java.lang.Override
        @JsonSetter("customer")
        public _FinalStage customer(@NotNull CreateCustomersRequestCustomer customer) {
            this.customer = Objects.requireNonNull(customer, "customer must not be null");
            return this;
        }

        /**
         * <p>When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes <code>apple_wallet_url</code> and <code>google_wallet_url</code> in each customer card object so you can deliver them yourself.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sendCardLinks(Boolean sendCardLinks) {
            this.sendCardLinks = Optional.ofNullable(sendCardLinks);
            return this;
        }

        /**
         * <p>When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes <code>apple_wallet_url</code> and <code>google_wallet_url</code> in each customer card object so you can deliver them yourself.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "send_card_links", nulls = Nulls.SKIP)
        public _FinalStage sendCardLinks(Optional<Boolean> sendCardLinks) {
            this.sendCardLinks = sendCardLinks;
            return this;
        }

        /**
         * <p>Loyalty card ID to auto-enroll the customer in</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage cardId(Integer cardId) {
            this.cardId = Optional.ofNullable(cardId);
            return this;
        }

        /**
         * <p>Loyalty card ID to auto-enroll the customer in</p>
         */
        @java.lang.Override
        @JsonSetter(value = "card_id", nulls = Nulls.SKIP)
        public _FinalStage cardId(Optional<Integer> cardId) {
            this.cardId = cardId;
            return this;
        }

        @java.lang.Override
        public CreateCustomersRequest build() {
            return new CreateCustomersRequest(cardId, customer, sendCardLinks, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
