/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.getleal.api.resources.customers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.getleal.api.core.ObjectMappers;
import com.getleal.api.resources.customers.types.UpdateCustomersRequestCustomer;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateCustomersRequest.Builder.class)
public final class UpdateCustomersRequest {
    private final UpdateCustomersRequestCustomer customer;

    private final Map<String, Object> additionalProperties;

    private UpdateCustomersRequest(UpdateCustomersRequestCustomer customer, Map<String, Object> additionalProperties) {
        this.customer = customer;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("customer")
    public UpdateCustomersRequestCustomer getCustomer() {
        return customer;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateCustomersRequest && equalTo((UpdateCustomersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateCustomersRequest other) {
        return customer.equals(other.customer);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.customer);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CustomerStage builder() {
        return new Builder();
    }

    public interface CustomerStage {
        _FinalStage customer(@NotNull UpdateCustomersRequestCustomer customer);

        Builder from(UpdateCustomersRequest other);
    }

    public interface _FinalStage {
        UpdateCustomersRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CustomerStage, _FinalStage {
        private UpdateCustomersRequestCustomer customer;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateCustomersRequest other) {
            customer(other.getCustomer());
            return this;
        }

        @java.lang.Override
        @JsonSetter("customer")
        public _FinalStage customer(@NotNull UpdateCustomersRequestCustomer customer) {
            this.customer = Objects.requireNonNull(customer, "customer must not be null");
            return this;
        }

        @java.lang.Override
        public UpdateCustomersRequest build() {
            return new UpdateCustomersRequest(customer, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
